packages:
  - apps/*
  - libs/*

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@nx/angular@23.2.1'
  - '@nx/devkit@23.2.1'
  - '@nx/docker@23.2.1'
  - '@nx/eslint-plugin@23.2.1'
  - '@nx/eslint@23.2.1'
  - '@nx/jest@23.2.1'
  - '@nx/js@23.2.1'
  - '@nx/module-federation@23.2.1'
  - '@nx/nest@23.2.1'
  - '@nx/node@23.2.1'
  - '@nx/nx-darwin-arm64@23.2.1'
  - '@nx/nx-darwin-x64@23.2.1'
  - '@nx/nx-freebsd-x64@23.2.1'
  - '@nx/nx-linux-arm-gnueabihf@23.2.1'
  - '@nx/nx-linux-arm64-gnu@23.2.1'
  - '@nx/nx-linux-arm64-musl@23.2.1'
  - '@nx/nx-linux-x64-gnu@23.2.1'
  - '@nx/nx-linux-x64-musl@23.2.1'
  - '@nx/nx-win32-arm64-msvc@23.2.1'
  - '@nx/nx-win32-x64-msvc@23.2.1'
  - '@nx/rspack@23.2.1'
  - '@nx/web@23.2.1'
  - '@nx/webpack@23.2.1'
  - '@nx/workspace@23.2.1'
  - nx@23.2.1
