import { Migration } from '@mikro-orm/migrations';

export class Migration20260502120000_ex56d2_project_cost_operating_enum_checks extends Migration {
    override async up(): Promise<void> {
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_cost_type";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_record_status";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_source_type";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_labor_period_type";`);
        this.addSql(`alter table "poms"."operating_baseline_package" drop constraint if exists "chk_operating_baseline_package_baseline_selection_source";`);
        this.addSql(`alter table "poms"."operating_baseline_package" drop constraint if exists "chk_operating_baseline_package_status";`);
        this.addSql(`alter table "poms"."change_package_baseline" drop constraint if exists "chk_change_package_baseline_status";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_snapshot_mode";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_current_action_level";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_baseline_selection_source";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_status";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_snapshot_mode";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_current_action_level";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_baseline_selection_source";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_status";`);
        this.addSql(`alter table "poms"."operating_restatement_record" drop constraint if exists "chk_operating_restatement_record_status";`);
        this.addSql(`alter table "poms"."shared_cost_allocation_basis" drop constraint if exists "chk_shared_cost_allocation_basis_status";`);
        this.addSql(`alter table "poms"."shared_cost_allocation_result" drop constraint if exists "chk_shared_cost_allocation_result_status";`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" drop constraint if exists "chk_cost_stage_attribution_snapshot_attribution_mode";`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" drop constraint if exists "chk_cost_stage_attribution_snapshot_status";`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" drop constraint if exists "chk_accounting_tax_treatment_snapshot_deductibility_status";`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" drop constraint if exists "chk_accounting_tax_treatment_snapshot_status";`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" drop constraint if exists "chk_data_maturity_evaluation_result_data_maturity_level";`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" drop constraint if exists "chk_data_maturity_evaluation_result_cost_action_recommendation";`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" drop constraint if exists "chk_data_maturity_evaluation_result_status";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_signal_level";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_risk_level";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_formula_boundary_action";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_current_action_level";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_status";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_review_decision";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_data_maturity_level";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_cost_action_recommendation";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_cost_action_recomme";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_current_action_level";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_current_action_leve";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_status";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_review_decision";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_resolved_cost_action";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_resolved_current_action";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_resolved_data_maturity";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_status";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_binding_action";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_baseline_selection_source";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_data_maturity_level";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_cost_action_recommendation";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_current_action_level";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_status";`);
        this.addSql(`alter table "poms"."commission_final_settlement_snapshot" drop constraint if exists "chk_cfss_data_maturity_level";`);

        this.addSql(`alter table "poms"."period_closing_snapshot" alter column "baseline_selection_source" set default 'original';`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" alter column "deductibility_status" set default 'pending';`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" alter column "attribution_mode" set default 'manual';`);
        this.addSql(`alter table "poms"."project_operating_snapshot" alter column "baseline_selection_source" set default 'original';`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" alter column "data_maturity_level" set default 'INSUFFICIENT';`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" alter column "cost_action_recommendation" set default 'REVIEW';`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "signal_level" set default 'ATTENTION';`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "risk_level" set default 'ATTENTION';`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "formula_boundary_action" set default 'PROMPT';`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "current_action_level" set default 'REVIEW';`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "binding_action" set default 'REVIEW';`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "baseline_selection_source" set default 'original';`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "data_maturity_level" set default 'INSUFFICIENT';`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "cost_action_recommendation" set default 'REVIEW';`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "current_action_level" set default 'REVIEW';`);
        this.addSql(`alter table "poms"."operating_signal_review_record" alter column "review_decision" set default 'APPROVE';`);

        this.addSql(`alter table "poms"."project_actual_cost_record" add constraint "chk_project_actual_cost_record_cost_type" check ("cost_type" in ('PROCUREMENT', 'INVOICE', 'EXPENSE', 'PAYMENT_FACT', 'LABOR'));`);
        this.addSql(`alter table "poms"."project_actual_cost_record" add constraint "chk_project_actual_cost_record_record_status" check ("record_status" in ('DRAFT', 'REGISTERED', 'CONFIRMED', 'INCLUDED', 'VOIDED', 'REPLACED'));`);
        this.addSql(`alter table "poms"."project_actual_cost_record" add constraint "chk_project_actual_cost_record_labor_period_type" check ("labor_period_type" is null or ("labor_period_type")::text = any ((array['WEEK'::character varying, 'MONTH'::character varying])::text[]));`);
        this.addSql(`alter table "poms"."project_actual_cost_record" add constraint "chk_project_actual_cost_record_source_type" check ("source_type" is null or ("source_type")::text = any ((array['PAYMENT_RECORD'::character varying, 'INVOICE_RECORD'::character varying, 'EXPENSE_RECORD'::character varying, 'PAYABLE_RECORD'::character varying, 'LABOR'::character varying])::text[]));`);
        this.addSql(`alter table "poms"."operating_baseline_package" add constraint "chk_operating_baseline_package_baseline_selection_source" check ("baseline_selection_source" in ('original', 'handover_rebaseline'));`);
        this.addSql(`alter table "poms"."operating_baseline_package" add constraint "chk_operating_baseline_package_status" check ("status" in ('draft', 'active', 'superseded'));`);
        this.addSql(`alter table "poms"."change_package_baseline" add constraint "chk_change_package_baseline_status" check ("status" in ('active', 'voided'));`);
        this.addSql(`alter table "poms"."project_operating_snapshot" add constraint "chk_project_operating_snapshot_snapshot_mode" check ("snapshot_mode" in ('realtime', 'period-end', 'restated'));`);
        this.addSql(`alter table "poms"."project_operating_snapshot" add constraint "chk_project_operating_snapshot_current_action_level" check ("current_action_level" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."project_operating_snapshot" add constraint "chk_project_operating_snapshot_baseline_selection_source" check ("baseline_selection_source" in ('original', 'handover_rebaseline'));`);
        this.addSql(`alter table "poms"."project_operating_snapshot" add constraint "chk_project_operating_snapshot_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."period_closing_snapshot" add constraint "chk_period_closing_snapshot_snapshot_mode" check ("snapshot_mode" in ('period-end'));`);
        this.addSql(`alter table "poms"."period_closing_snapshot" add constraint "chk_period_closing_snapshot_current_action_level" check ("current_action_level" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."period_closing_snapshot" add constraint "chk_period_closing_snapshot_baseline_selection_source" check ("baseline_selection_source" in ('original', 'handover_rebaseline'));`);
        this.addSql(`alter table "poms"."period_closing_snapshot" add constraint "chk_period_closing_snapshot_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."operating_restatement_record" add constraint "chk_operating_restatement_record_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."shared_cost_allocation_basis" add constraint "chk_shared_cost_allocation_basis_status" check ("status" in ('pending', 'active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."shared_cost_allocation_result" add constraint "chk_shared_cost_allocation_result_status" check ("status" in ('pending', 'active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" add constraint "chk_cost_stage_attribution_snapshot_attribution_mode" check ("attribution_mode" in ('auto', 'manual', 'reclassified'));`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" add constraint "chk_cost_stage_attribution_snapshot_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" add constraint "chk_accounting_tax_treatment_snapshot_deductibility_status" check ("deductibility_status" in ('pending', 'deductible', 'non-deductible'));`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" add constraint "chk_accounting_tax_treatment_snapshot_status" check ("status" in ('pending', 'active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" add constraint "chk_data_maturity_evaluation_result_data_maturity_level" check ("data_maturity_level" in ('INSUFFICIENT', 'PRELIMINARY', 'MATURE'));`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" add constraint "chk_data_maturity_evaluation_result_cost_action_recommendation" check ("cost_action_recommendation" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" add constraint "chk_data_maturity_evaluation_result_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" add constraint "chk_operating_signal_evaluation_result_signal_level" check ("signal_level" in ('ATTENTION', 'ALERT'));`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" add constraint "chk_operating_signal_evaluation_result_risk_level" check ("risk_level" in ('ATTENTION', 'RISK'));`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" add constraint "chk_operating_signal_evaluation_result_formula_boundary_action" check ("formula_boundary_action" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" add constraint "chk_operating_signal_evaluation_result_current_action_level" check ("current_action_level" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" add constraint "chk_operating_signal_evaluation_result_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."operating_signal_review_record" add constraint "chk_os_review_review_decision" check ("review_decision" in ('APPROVE', 'MANUAL_CONFIRMED'));`);
        this.addSql(`alter table "poms"."operating_signal_review_record" add constraint "chk_os_review_resolved_cost_action" check ("resolved_cost_action_recommendation" is null or ("resolved_cost_action_recommendation")::text = any ((array['PROMPT'::character varying, 'REVIEW'::character varying, 'BLOCK'::character varying])::text[]));`);
        this.addSql(`alter table "poms"."operating_signal_review_record" add constraint "chk_os_review_resolved_current_action" check ("resolved_current_action_level" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."operating_signal_review_record" add constraint "chk_os_review_resolved_data_maturity" check ("resolved_data_maturity_level" is null or ("resolved_data_maturity_level")::text = any ((array['INSUFFICIENT'::character varying, 'PRELIMINARY'::character varying, 'MATURE'::character varying])::text[]));`);
        this.addSql(`alter table "poms"."operating_signal_review_record" add constraint "chk_os_review_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" add constraint "chk_operating_signal_gate_binding_binding_action" check ("binding_action" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" add constraint "chk_operating_signal_gate_binding_baseline_selection_source" check ("baseline_selection_source" in ('original', 'handover_rebaseline'));`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" add constraint "chk_operating_signal_gate_binding_data_maturity_level" check ("data_maturity_level" in ('INSUFFICIENT', 'PRELIMINARY', 'MATURE'));`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" add constraint "chk_operating_signal_gate_binding_cost_action_recommendation" check ("cost_action_recommendation" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" add constraint "chk_operating_signal_gate_binding_current_action_level" check ("current_action_level" in ('PROMPT', 'REVIEW', 'BLOCK'));`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" add constraint "chk_operating_signal_gate_binding_status" check ("status" in ('active', 'superseded', 'voided'));`);
        this.addSql(`alter table "poms"."commission_final_settlement_snapshot" add constraint "chk_cfss_data_maturity_level" check ("data_maturity_level" in ('INSUFFICIENT', 'PRELIMINARY', 'MATURE'));`);
    }

    override async down(): Promise<void> {
        this.addSql(`alter table "poms"."commission_final_settlement_snapshot" drop constraint if exists "chk_cfss_data_maturity_level";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_status";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_current_action_level";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_cost_action_recommendation";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_data_maturity_level";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_baseline_selection_source";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" drop constraint if exists "chk_operating_signal_gate_binding_binding_action";`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "current_action_level" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "cost_action_recommendation" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "data_maturity_level" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "baseline_selection_source" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_gate_binding" alter column "binding_action" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_status";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_resolved_data_maturity";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_resolved_current_action";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_resolved_cost_action";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_os_review_review_decision";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_status";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_current_action_level";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_current_action_leve";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_cost_action_recommendation";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_cost_action_recomme";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_resolved_data_maturity_level";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" drop constraint if exists "chk_operating_signal_review_record_review_decision";`);
        this.addSql(`alter table "poms"."operating_signal_review_record" alter column "review_decision" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_status";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_current_action_level";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_formula_boundary_action";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_risk_level";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" drop constraint if exists "chk_operating_signal_evaluation_result_signal_level";`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "current_action_level" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "formula_boundary_action" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "risk_level" drop default;`);
        this.addSql(`alter table "poms"."operating_signal_evaluation_result" alter column "signal_level" drop default;`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" drop constraint if exists "chk_data_maturity_evaluation_result_status";`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" drop constraint if exists "chk_data_maturity_evaluation_result_cost_action_recommendation";`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" drop constraint if exists "chk_data_maturity_evaluation_result_data_maturity_level";`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" alter column "cost_action_recommendation" drop default;`);
        this.addSql(`alter table "poms"."data_maturity_evaluation_result" alter column "data_maturity_level" drop default;`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" drop constraint if exists "chk_accounting_tax_treatment_snapshot_status";`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" drop constraint if exists "chk_accounting_tax_treatment_snapshot_deductibility_status";`);
        this.addSql(`alter table "poms"."accounting_tax_treatment_snapshot" alter column "deductibility_status" drop default;`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" drop constraint if exists "chk_cost_stage_attribution_snapshot_status";`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" drop constraint if exists "chk_cost_stage_attribution_snapshot_attribution_mode";`);
        this.addSql(`alter table "poms"."cost_stage_attribution_snapshot" alter column "attribution_mode" drop default;`);
        this.addSql(`alter table "poms"."shared_cost_allocation_result" drop constraint if exists "chk_shared_cost_allocation_result_status";`);
        this.addSql(`alter table "poms"."shared_cost_allocation_basis" drop constraint if exists "chk_shared_cost_allocation_basis_status";`);
        this.addSql(`alter table "poms"."operating_restatement_record" drop constraint if exists "chk_operating_restatement_record_status";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_status";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_baseline_selection_source";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_current_action_level";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" drop constraint if exists "chk_period_closing_snapshot_snapshot_mode";`);
        this.addSql(`alter table "poms"."period_closing_snapshot" alter column "baseline_selection_source" drop default;`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_status";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_baseline_selection_source";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_current_action_level";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" drop constraint if exists "chk_project_operating_snapshot_snapshot_mode";`);
        this.addSql(`alter table "poms"."project_operating_snapshot" alter column "baseline_selection_source" drop default;`);
        this.addSql(`alter table "poms"."change_package_baseline" drop constraint if exists "chk_change_package_baseline_status";`);
        this.addSql(`alter table "poms"."operating_baseline_package" drop constraint if exists "chk_operating_baseline_package_status";`);
        this.addSql(`alter table "poms"."operating_baseline_package" drop constraint if exists "chk_operating_baseline_package_baseline_selection_source";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_labor_period_type";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_source_type";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_record_status";`);
        this.addSql(`alter table "poms"."project_actual_cost_record" drop constraint if exists "chk_project_actual_cost_record_cost_type";`);
    }
}
