import { Migration } from '@mikro-orm/migrations';

export class Migration20260414111805_ex07a_add_comments extends Migration {

  override up(): void | Promise<void> {
    this.addSql(`comment on column "poms"."period_closing_snapshot"."id" is '主键';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."project_id" is '关联项目';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."period_key" is '期间键（格式：YYYY-MM 或 YYYY-Www）';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."snapshot_mode" is '快照模式：period-end';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."snapshot_at" is '快照生成时点';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."effective_contract_total" is '当前有效合同总额';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."receivable_confirmed_total" is '已确认回款总额';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."included_cost_total" is '已纳入口径成本总额';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."original_baseline_cost" is '原始签约基线成本';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."current_effective_baseline_cost" is '当前有效基线成本';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."gross_margin_amount" is '毛利金额';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."gross_margin_rate" is '毛利率';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."tax_impact_summary" is '税务影响摘要';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."tax_impact_pending_amount" is '待确认税务影响金额';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."allocation_stability_summary" is '分摊稳定性摘要';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."unmapped_cost_summary" is '未映射成本摘要';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."current_action_level" is '当前动作等级：PROMPT/REVIEW/BLOCK';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."referenced_baseline_version" is '引用基线版本标识';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."baseline_selection_source" is '基线选择来源：original/handover_rebaseline';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."handover_rebaseline_record_id" is '移交前再基线化记录 ID（FK 待 EX-08 补加）';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."status" is '状态：active/superseded/voided';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."period_closing_snapshot" is '期末冻结快照（按期间锁定经营口径）';`);

    this.addSql(`comment on column "poms"."operating_baseline_package"."id" is '主键';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."project_id" is '关联项目';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."original_baseline_cost" is '原始签约基线成本';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."change_package_total" is '已批准变更包累计金额';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."current_effective_baseline_cost" is '当前有效基线成本 = 原始 + 变更包';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."baseline_selection_source" is '基线来源：original/handover_rebaseline';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."effective_operating_baseline_id" is '生效的经营基线引用 ID';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."baseline_summary" is '基线说明';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."is_current" is '是否为当前有效基线包';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."status" is '状态：draft/active/superseded';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."effective_at" is '生效时间';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."effective_by" is '生效操作人';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."operating_baseline_package" is '经营基线包（原始签约基线 + 变更包汇总）';`);

    this.addSql(`comment on column "poms"."change_package_baseline"."id" is '主键';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."baseline_package_id" is '关联经营基线包';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."change_package_id" is '变更包标识';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."change_amount" is '变更金额（正增负减）';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."change_summary" is '变更包说明';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."status" is '状态：active/voided';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."effective_at" is '生效时间';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."change_package_baseline"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."change_package_baseline" is '已批准变更包基线明细';`);

    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."id" is '主键';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."project_id" is '关联项目';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_treatment_type" is '税务处理类型';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."deductibility_status" is '可抵扣状态';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_impact_amount" is '税务影响金额';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_pending_flag" is '是否存在待确认税务影响';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_impact_summary" is '税务影响摘要（供 L4/L5 稳定消费）';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_impact_pending_amount" is '待确认税务影响金额';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."basis_summary" is '判断依据摘要';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."status" is '状态：pending/active/superseded/voided';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."supersedes_id" is '被替代的旧税务处理快照 ID';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."confirmed_at" is '确认时间';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."confirmed_by" is '确认人';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."accounting_tax_treatment_snapshot" is '税务处理与核算口径快照';`);

    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."id" is '主键';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."cost_record_id" is '关联成本记录';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."attributed_stage" is '归属执行阶段';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."attribution_mode" is '归属模式：auto/manual/reclassified';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."locked_by_snapshot_id" is '锁定快照 ID';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."attribution_summary" is '归属依据说明';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."status" is '状态：active/superseded/voided';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."supersedes_id" is '被替代的旧归属快照 ID';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."handled_at" is '操作时间';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."handled_by" is '操作人';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."cost_stage_attribution_snapshot" is '成本阶段归属锁定与重分类快照';`);

    this.addSql(`comment on column "poms"."project_operating_snapshot"."id" is '主键';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."project_id" is '关联项目';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."snapshot_mode" is '快照模式：realtime/period-end/restated';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."snapshot_at" is '快照时点';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."source_window_start" is '来源窗口开始日期';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."source_window_end" is '来源窗口结束日期';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."effective_contract_total" is '当前有效合同总额';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."receivable_confirmed_total" is '已确认回款总额';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."included_cost_total" is '已纳入口径成本总额';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."original_baseline_cost" is '原始签约基线成本';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."current_effective_baseline_cost" is '当前有效基线成本';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."gross_margin_amount" is '毛利金额';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."gross_margin_rate" is '毛利率';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."tax_impact_summary" is '税务影响摘要（供 L4/L5 稳定消费）';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."tax_impact_pending_amount" is '待确认税务影响金额';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."allocation_stability_summary" is '分摊稳定性摘要';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."unmapped_cost_summary" is '未映射成本摘要';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."current_action_level" is '当前动作等级：PROMPT/REVIEW/BLOCK';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."referenced_baseline_version" is '引用基线版本标识';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."baseline_selection_source" is '基线选择来源：original/handover_rebaseline';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."handover_rebaseline_record_id" is '移交前再基线化记录 ID（FK 待 EX-08 补加）';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."status" is '状态：active/superseded/voided';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."supersedes_id" is '被替代的旧快照 ID';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."project_operating_snapshot" is '项目实时 / 历史经营快照（L2 稳定结果锚点）';`);

    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."id" is '主键';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."source_cost_scope_key" is '来源成本范围键';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."basis_type" is '分摊依据类型';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."allocation_method" is '分摊方法';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."basis_summary" is '分摊依据摘要';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."status" is '状态：pending/active/superseded/voided';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."effective_at" is '生效时间';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."effective_by" is '生效操作人';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."supersedes_id" is '被替代的旧依据 ID';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."shared_cost_allocation_basis" is '共享成本分摊依据主表';`);

    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."id" is '主键';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."basis_id" is '关联分摊依据';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."project_id" is '关联项目';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."allocated_amount" is '分摊金额';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."allocation_ratio" is '分摊比例';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."allocation_summary" is '分摊结果说明';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."status" is '状态：pending/active/superseded/voided';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."effective_at" is '生效时间';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."supersedes_id" is '被替代的旧结果 ID';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."created_at" is '创建时间';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."created_by" is '创建人';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."updated_at" is '最后更新时间';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."updated_by" is '最后更新人';`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."row_version" is '乐观锁版本号';`);
    this.addSql(`comment on table "poms"."shared_cost_allocation_result" is '共享成本分摊结果表';`);
  }

  override down(): void | Promise<void> {
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."id" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."project_id" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_treatment_type" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."deductibility_status" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_impact_amount" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_pending_flag" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_impact_summary" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."tax_impact_pending_amount" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."basis_summary" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."status" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."supersedes_id" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."confirmed_at" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."confirmed_by" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."created_at" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."created_by" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."accounting_tax_treatment_snapshot"."row_version" is null;`);
    this.addSql(`comment on table "poms"."accounting_tax_treatment_snapshot" is '';`);

    this.addSql(`comment on column "poms"."change_package_baseline"."id" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."baseline_package_id" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."change_package_id" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."change_amount" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."change_summary" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."status" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."effective_at" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."created_at" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."created_by" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."change_package_baseline"."row_version" is null;`);
    this.addSql(`comment on table "poms"."change_package_baseline" is '';`);

    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."id" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."cost_record_id" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."attributed_stage" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."attribution_mode" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."locked_by_snapshot_id" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."attribution_summary" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."status" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."supersedes_id" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."handled_at" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."handled_by" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."created_at" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."created_by" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."cost_stage_attribution_snapshot"."row_version" is null;`);
    this.addSql(`comment on table "poms"."cost_stage_attribution_snapshot" is '';`);

    this.addSql(`comment on column "poms"."operating_baseline_package"."id" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."project_id" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."original_baseline_cost" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."change_package_total" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."current_effective_baseline_cost" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."baseline_selection_source" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."effective_operating_baseline_id" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."baseline_summary" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."is_current" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."status" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."effective_at" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."effective_by" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."created_at" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."created_by" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."operating_baseline_package"."row_version" is null;`);
    this.addSql(`comment on table "poms"."operating_baseline_package" is '';`);

    this.addSql(`comment on column "poms"."period_closing_snapshot"."id" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."project_id" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."period_key" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."snapshot_mode" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."snapshot_at" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."effective_contract_total" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."receivable_confirmed_total" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."included_cost_total" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."original_baseline_cost" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."current_effective_baseline_cost" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."gross_margin_amount" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."gross_margin_rate" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."tax_impact_summary" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."tax_impact_pending_amount" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."allocation_stability_summary" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."unmapped_cost_summary" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."current_action_level" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."referenced_baseline_version" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."baseline_selection_source" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."handover_rebaseline_record_id" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."status" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."created_at" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."created_by" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."period_closing_snapshot"."row_version" is null;`);
    this.addSql(`comment on table "poms"."period_closing_snapshot" is '';`);

    this.addSql(`comment on column "poms"."project_operating_snapshot"."id" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."project_id" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."snapshot_mode" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."snapshot_at" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."source_window_start" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."source_window_end" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."effective_contract_total" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."receivable_confirmed_total" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."included_cost_total" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."original_baseline_cost" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."current_effective_baseline_cost" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."gross_margin_amount" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."gross_margin_rate" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."tax_impact_summary" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."tax_impact_pending_amount" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."allocation_stability_summary" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."unmapped_cost_summary" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."current_action_level" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."referenced_baseline_version" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."baseline_selection_source" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."handover_rebaseline_record_id" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."status" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."supersedes_id" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."created_at" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."created_by" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."project_operating_snapshot"."row_version" is null;`);
    this.addSql(`comment on table "poms"."project_operating_snapshot" is '';`);

    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."id" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."source_cost_scope_key" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."basis_type" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."allocation_method" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."basis_summary" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."status" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."effective_at" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."effective_by" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."supersedes_id" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."created_at" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."created_by" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_basis"."row_version" is null;`);
    this.addSql(`comment on table "poms"."shared_cost_allocation_basis" is '';`);

    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."id" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."basis_id" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."project_id" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."allocated_amount" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."allocation_ratio" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."allocation_summary" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."status" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."effective_at" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."supersedes_id" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."created_at" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."created_by" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."updated_at" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."updated_by" is null;`);
    this.addSql(`comment on column "poms"."shared_cost_allocation_result"."row_version" is null;`);
    this.addSql(`comment on table "poms"."shared_cost_allocation_result" is '';`);
  }

}
