export * from './app.service';
import { AppApi } from './app.service';
export * from './approval.service';
import { ApprovalApi } from './approval.service';
export * from './auth.service';
import { AuthApi } from './auth.service';
export * from './commission.service';
import { CommissionApi } from './commission.service';
export * from './contract.service';
import { ContractApi } from './contract.service';
export * from './contract-finance.service';
import { ContractFinanceApi } from './contract-finance.service';
export * from './navigation.service';
import { NavigationApi } from './navigation.service';
export * from './platform.service';
import { PlatformApi } from './platform.service';
export * from './project.service';
import { ProjectApi } from './project.service';
export * from './runtime-audit.service';
import { RuntimeAuditApi } from './runtime-audit.service';
export const APIS = [AppApi, ApprovalApi, AuthApi, CommissionApi, ContractApi, ContractFinanceApi, NavigationApi, PlatformApi, ProjectApi, RuntimeAuditApi];
