export * from './app.service';
import { AppApi } from './app.service';
export * from './approval.service';
import { ApprovalApi } from './approval.service';
export * from './attachment.service';
import { AttachmentApi } from './attachment.service';
export * from './attachment-handover.service';
import { AttachmentHandoverApi } from './attachment-handover.service';
export * from './attachment-storage-provider.service';
import { AttachmentStorageProviderApi } from './attachment-storage-provider.service';
export * from './attachment-upload-session.service';
import { AttachmentUploadSessionApi } from './attachment-upload-session.service';
export * from './auth.service';
import { AuthApi } from './auth.service';
export * from './business-discussion.service';
import { BusinessDiscussionApi } from './business-discussion.service';
export * from './commission.service';
import { CommissionApi } from './commission.service';
export * from './commission-departure-exception-decisions.service';
import { CommissionDepartureExceptionDecisionsApi } from './commission-departure-exception-decisions.service';
export * from './commission-freeze-change-requests.service';
import { CommissionFreezeChangeRequestsApi } from './commission-freeze-change-requests.service';
export * from './commission-freeze-disputes.service';
import { CommissionFreezeDisputesApi } from './commission-freeze-disputes.service';
export * from './commission-role-assignments.service';
import { CommissionRoleAssignmentsApi } from './commission-role-assignments.service';
export * from './contract.service';
import { ContractApi } from './contract.service';
export * from './contract-finance.service';
import { ContractFinanceApi } from './contract-finance.service';
export * from './contract-readiness.service';
import { ContractReadinessApi } from './contract-readiness.service';
export * from './customer.service';
import { CustomerApi } from './customer.service';
export * from './dictionary.service';
import { DictionaryApi } from './dictionary.service';
export * from './external-identity.service';
import { ExternalIdentityApi } from './external-identity.service';
export * from './health.service';
import { HealthApi } from './health.service';
export * from './identity-provider.service';
import { IdentityProviderApi } from './identity-provider.service';
export * from './identity-provider-o-auth-grant.service';
import { IdentityProviderOAuthGrantApi } from './identity-provider-o-auth-grant.service';
export * from './lead.service';
import { LeadApi } from './lead.service';
export * from './navigation.service';
import { NavigationApi } from './navigation.service';
export * from './platform.service';
import { PlatformApi } from './platform.service';
export * from './project.service';
import { ProjectApi } from './project.service';
export * from './project-cost.service';
import { ProjectCostApi } from './project-cost.service';
export * from './project-handover.service';
import { ProjectHandoverApi } from './project-handover.service';
export * from './runtime-audit.service';
import { RuntimeAuditApi } from './runtime-audit.service';
export * from './sales-follow-up.service';
import { SalesFollowUpApi } from './sales-follow-up.service';
export * from './sales-intelligence.service';
import { SalesIntelligenceApi } from './sales-intelligence.service';
export * from './system-setting.service';
import { SystemSettingApi } from './system-setting.service';
export const APIS = [AppApi, ApprovalApi, AttachmentApi, AttachmentHandoverApi, AttachmentStorageProviderApi, AttachmentUploadSessionApi, AuthApi, BusinessDiscussionApi, CommissionApi, CommissionDepartureExceptionDecisionsApi, CommissionFreezeChangeRequestsApi, CommissionFreezeDisputesApi, CommissionRoleAssignmentsApi, ContractApi, ContractFinanceApi, ContractReadinessApi, CustomerApi, DictionaryApi, ExternalIdentityApi, HealthApi, IdentityProviderApi, IdentityProviderOAuthGrantApi, LeadApi, NavigationApi, PlatformApi, ProjectApi, ProjectCostApi, ProjectHandoverApi, RuntimeAuditApi, SalesFollowUpApi, SalesIntelligenceApi, SystemSettingApi];
