/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { AttachmentDownloadPackageSummary } from '../model/attachment-download-package-summary';
// @ts-ignore
import { CreateProjectHandoverAttachmentDownloadPackageRequest } from '../model/create-project-handover-attachment-download-package-request';
// @ts-ignore
import { ProjectHandoverAttachmentChecklistView } from '../model/project-handover-attachment-checklist-view';
// @ts-ignore
import { RefreshProjectHandoverAttachmentChecklistRequest } from '../model/refresh-project-handover-attachment-checklist-request';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { PomsApiConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface AttachmentHandoverControllerCreateDownloadPackageRequestParams {
    handoverId: string;
    createProjectHandoverAttachmentDownloadPackageRequest: CreateProjectHandoverAttachmentDownloadPackageRequest;
}

export interface AttachmentHandoverControllerDownloadPackageRequestParams {
    packageId: string;
}

export interface AttachmentHandoverControllerGetChecklistRequestParams {
    handoverId: string;
}

export interface AttachmentHandoverControllerGetDownloadPackageRequestParams {
    packageId: string;
}

export interface AttachmentHandoverControllerRefreshChecklistRequestParams {
    handoverId: string;
    refreshProjectHandoverAttachmentChecklistRequest: RefreshProjectHandoverAttachmentChecklistRequest;
}


@Injectable({
  providedIn: 'root'
})
export class AttachmentHandoverApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: PomsApiConfiguration) {
        super(basePath, configuration);
    }

    /**
     * 创建项目移交附件批量下载包
     * @endpoint post /api/project-handovers/{handoverId}/attachment-download-packages
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public attachmentHandoverControllerCreateDownloadPackage(requestParameters: AttachmentHandoverControllerCreateDownloadPackageRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AttachmentDownloadPackageSummary>;
    public attachmentHandoverControllerCreateDownloadPackage(requestParameters: AttachmentHandoverControllerCreateDownloadPackageRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AttachmentDownloadPackageSummary>>;
    public attachmentHandoverControllerCreateDownloadPackage(requestParameters: AttachmentHandoverControllerCreateDownloadPackageRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AttachmentDownloadPackageSummary>>;
    public attachmentHandoverControllerCreateDownloadPackage(requestParameters: AttachmentHandoverControllerCreateDownloadPackageRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const handoverId = requestParameters?.handoverId;
        if (handoverId === null || handoverId === undefined) {
            throw new Error('Required parameter handoverId was null or undefined when calling attachmentHandoverControllerCreateDownloadPackage.');
        }
        const createProjectHandoverAttachmentDownloadPackageRequest = requestParameters?.createProjectHandoverAttachmentDownloadPackageRequest;
        if (createProjectHandoverAttachmentDownloadPackageRequest === null || createProjectHandoverAttachmentDownloadPackageRequest === undefined) {
            throw new Error('Required parameter createProjectHandoverAttachmentDownloadPackageRequest was null or undefined when calling attachmentHandoverControllerCreateDownloadPackage.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/project-handovers/${this.configuration.encodeParam({name: "handoverId", value: handoverId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/attachment-download-packages`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AttachmentDownloadPackageSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createProjectHandoverAttachmentDownloadPackageRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 下载附件批量包
     * @endpoint get /api/attachment-download-packages/{packageId}/download
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public attachmentHandoverControllerDownloadPackage(requestParameters: AttachmentHandoverControllerDownloadPackageRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public attachmentHandoverControllerDownloadPackage(requestParameters: AttachmentHandoverControllerDownloadPackageRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public attachmentHandoverControllerDownloadPackage(requestParameters: AttachmentHandoverControllerDownloadPackageRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public attachmentHandoverControllerDownloadPackage(requestParameters: AttachmentHandoverControllerDownloadPackageRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const packageId = requestParameters?.packageId;
        if (packageId === null || packageId === undefined) {
            throw new Error('Required parameter packageId was null or undefined when calling attachmentHandoverControllerDownloadPackage.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/attachment-download-packages/${this.configuration.encodeParam({name: "packageId", value: packageId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/download`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取项目移交附件清单
     * @endpoint get /api/project-handovers/{handoverId}/attachment-checklist
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public attachmentHandoverControllerGetChecklist(requestParameters: AttachmentHandoverControllerGetChecklistRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ProjectHandoverAttachmentChecklistView>;
    public attachmentHandoverControllerGetChecklist(requestParameters: AttachmentHandoverControllerGetChecklistRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ProjectHandoverAttachmentChecklistView>>;
    public attachmentHandoverControllerGetChecklist(requestParameters: AttachmentHandoverControllerGetChecklistRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ProjectHandoverAttachmentChecklistView>>;
    public attachmentHandoverControllerGetChecklist(requestParameters: AttachmentHandoverControllerGetChecklistRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const handoverId = requestParameters?.handoverId;
        if (handoverId === null || handoverId === undefined) {
            throw new Error('Required parameter handoverId was null or undefined when calling attachmentHandoverControllerGetChecklist.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/project-handovers/${this.configuration.encodeParam({name: "handoverId", value: handoverId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/attachment-checklist`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ProjectHandoverAttachmentChecklistView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取附件下载包状态
     * @endpoint get /api/attachment-download-packages/{packageId}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public attachmentHandoverControllerGetDownloadPackage(requestParameters: AttachmentHandoverControllerGetDownloadPackageRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AttachmentDownloadPackageSummary>;
    public attachmentHandoverControllerGetDownloadPackage(requestParameters: AttachmentHandoverControllerGetDownloadPackageRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AttachmentDownloadPackageSummary>>;
    public attachmentHandoverControllerGetDownloadPackage(requestParameters: AttachmentHandoverControllerGetDownloadPackageRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AttachmentDownloadPackageSummary>>;
    public attachmentHandoverControllerGetDownloadPackage(requestParameters: AttachmentHandoverControllerGetDownloadPackageRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const packageId = requestParameters?.packageId;
        if (packageId === null || packageId === undefined) {
            throw new Error('Required parameter packageId was null or undefined when calling attachmentHandoverControllerGetDownloadPackage.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/attachment-download-packages/${this.configuration.encodeParam({name: "packageId", value: packageId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AttachmentDownloadPackageSummary>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 刷新项目移交附件清单
     * @endpoint post /api/project-handovers/{handoverId}/attachment-checklist:refresh
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public attachmentHandoverControllerRefreshChecklist(requestParameters: AttachmentHandoverControllerRefreshChecklistRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ProjectHandoverAttachmentChecklistView>;
    public attachmentHandoverControllerRefreshChecklist(requestParameters: AttachmentHandoverControllerRefreshChecklistRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ProjectHandoverAttachmentChecklistView>>;
    public attachmentHandoverControllerRefreshChecklist(requestParameters: AttachmentHandoverControllerRefreshChecklistRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ProjectHandoverAttachmentChecklistView>>;
    public attachmentHandoverControllerRefreshChecklist(requestParameters: AttachmentHandoverControllerRefreshChecklistRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const handoverId = requestParameters?.handoverId;
        if (handoverId === null || handoverId === undefined) {
            throw new Error('Required parameter handoverId was null or undefined when calling attachmentHandoverControllerRefreshChecklist.');
        }
        const refreshProjectHandoverAttachmentChecklistRequest = requestParameters?.refreshProjectHandoverAttachmentChecklistRequest;
        if (refreshProjectHandoverAttachmentChecklistRequest === null || refreshProjectHandoverAttachmentChecklistRequest === undefined) {
            throw new Error('Required parameter refreshProjectHandoverAttachmentChecklistRequest was null or undefined when calling attachmentHandoverControllerRefreshChecklist.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/project-handovers/${this.configuration.encodeParam({name: "handoverId", value: handoverId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/attachment-checklist:refresh`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ProjectHandoverAttachmentChecklistView>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: refreshProjectHandoverAttachmentChecklistRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
