/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ArbitrateCommissionFreezeDisputeRequest } from '../model/arbitrate-commission-freeze-dispute-request';
// @ts-ignore
import { ArbitrateCommissionFreezeDisputeResult } from '../model/arbitrate-commission-freeze-dispute-result';
// @ts-ignore
import { CommissionFreezeDisputeDetailView } from '../model/commission-freeze-dispute-detail-view';
// @ts-ignore
import { SubmitCommissionFreezeDisputeRequest } from '../model/submit-commission-freeze-dispute-request';
// @ts-ignore
import { SubmitCommissionFreezeDisputeResult } from '../model/submit-commission-freeze-dispute-result';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { PomsApiConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface CommissionFreezeDisputeControllerArbitrateCommissionFreezeDisputeRequestParams {
    id: string;
    arbitrateCommissionFreezeDisputeRequest: ArbitrateCommissionFreezeDisputeRequest;
}

export interface CommissionFreezeDisputeControllerGetCommissionFreezeDisputeRequestParams {
    id: string;
}

export interface CommissionFreezeDisputeControllerSubmitCommissionFreezeDisputeRequestParams {
    submitCommissionFreezeDisputeRequest: SubmitCommissionFreezeDisputeRequest;
}


@Injectable({
  providedIn: 'root'
})
export class CommissionFreezeDisputesApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: PomsApiConfiguration) {
        super(basePath, configuration);
    }

    /**
     * 仲裁提成冻结争议并生成受控变更链
     * @endpoint post /api/commission-freeze-disputes/{id}:arbitrate
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public commissionFreezeDisputeControllerArbitrateCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerArbitrateCommissionFreezeDisputeRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ArbitrateCommissionFreezeDisputeResult>;
    public commissionFreezeDisputeControllerArbitrateCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerArbitrateCommissionFreezeDisputeRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ArbitrateCommissionFreezeDisputeResult>>;
    public commissionFreezeDisputeControllerArbitrateCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerArbitrateCommissionFreezeDisputeRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ArbitrateCommissionFreezeDisputeResult>>;
    public commissionFreezeDisputeControllerArbitrateCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerArbitrateCommissionFreezeDisputeRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling commissionFreezeDisputeControllerArbitrateCommissionFreezeDispute.');
        }
        const arbitrateCommissionFreezeDisputeRequest = requestParameters?.arbitrateCommissionFreezeDisputeRequest;
        if (arbitrateCommissionFreezeDisputeRequest === null || arbitrateCommissionFreezeDisputeRequest === undefined) {
            throw new Error('Required parameter arbitrateCommissionFreezeDisputeRequest was null or undefined when calling commissionFreezeDisputeControllerArbitrateCommissionFreezeDispute.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commission-freeze-disputes/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:arbitrate`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ArbitrateCommissionFreezeDisputeResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: arbitrateCommissionFreezeDisputeRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取提成冻结争议详情
     * @endpoint get /api/commission-freeze-disputes/{id}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public commissionFreezeDisputeControllerGetCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerGetCommissionFreezeDisputeRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CommissionFreezeDisputeDetailView>;
    public commissionFreezeDisputeControllerGetCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerGetCommissionFreezeDisputeRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CommissionFreezeDisputeDetailView>>;
    public commissionFreezeDisputeControllerGetCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerGetCommissionFreezeDisputeRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CommissionFreezeDisputeDetailView>>;
    public commissionFreezeDisputeControllerGetCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerGetCommissionFreezeDisputeRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling commissionFreezeDisputeControllerGetCommissionFreezeDispute.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commission-freeze-disputes/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CommissionFreezeDisputeDetailView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 提交提成冻结后争议
     * @endpoint post /api/commission-freeze-disputes
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public commissionFreezeDisputeControllerSubmitCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerSubmitCommissionFreezeDisputeRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<SubmitCommissionFreezeDisputeResult>;
    public commissionFreezeDisputeControllerSubmitCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerSubmitCommissionFreezeDisputeRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SubmitCommissionFreezeDisputeResult>>;
    public commissionFreezeDisputeControllerSubmitCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerSubmitCommissionFreezeDisputeRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SubmitCommissionFreezeDisputeResult>>;
    public commissionFreezeDisputeControllerSubmitCommissionFreezeDispute(requestParameters: CommissionFreezeDisputeControllerSubmitCommissionFreezeDisputeRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const submitCommissionFreezeDisputeRequest = requestParameters?.submitCommissionFreezeDisputeRequest;
        if (submitCommissionFreezeDisputeRequest === null || submitCommissionFreezeDisputeRequest === undefined) {
            throw new Error('Required parameter submitCommissionFreezeDisputeRequest was null or undefined when calling commissionFreezeDisputeControllerSubmitCommissionFreezeDispute.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commission-freeze-disputes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SubmitCommissionFreezeDisputeResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: submitCommissionFreezeDisputeRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
