/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { CommercialDiffReviewResult } from '../model/commercial-diff-review-result';
// @ts-ignore
import { CommercialReleaseBaselineSummary } from '../model/commercial-release-baseline-summary';
// @ts-ignore
import { ContractDiffReviewHistoryView } from '../model/contract-diff-review-history-view';
// @ts-ignore
import { ContractReadinessDetail } from '../model/contract-readiness-detail';
// @ts-ignore
import { CreateCommercialReleaseBaselineRequest } from '../model/create-commercial-release-baseline-request';
// @ts-ignore
import { CreateContractReadinessPackageRequest } from '../model/create-contract-readiness-package-request';
// @ts-ignore
import { InitializeContractSnapshotFromReadinessPackageRequest } from '../model/initialize-contract-snapshot-from-readiness-package-request';
// @ts-ignore
import { InitializeReceivablePlanFromReadinessPackageRequest } from '../model/initialize-receivable-plan-from-readiness-package-request';
// @ts-ignore
import { ReadinessInitializationResult } from '../model/readiness-initialization-result';
// @ts-ignore
import { ReviewCommercialReleaseBaselineDiffRequest } from '../model/review-commercial-release-baseline-diff-request';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { PomsApiConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface ContractReadinessControllerCreateCommercialReleaseBaselineRequestParams {
    createCommercialReleaseBaselineRequest: CreateCommercialReleaseBaselineRequest;
}

export interface ContractReadinessControllerCreateContractReadinessPackageRequestParams {
    createContractReadinessPackageRequest: CreateContractReadinessPackageRequest;
}

export interface ContractReadinessControllerGetCommercialReleaseBaselineRequestParams {
    id: string;
}

export interface ContractReadinessControllerGetContractReadinessPackageRequestParams {
    id: string;
}

export interface ContractReadinessControllerGetCurrentContractReadinessRequestParams {
    projectId: string;
}

export interface ContractReadinessControllerGetDiffHistoryRequestParams {
    id: string;
}

export interface ContractReadinessControllerInitializeContractSnapshotRequestParams {
    id: string;
    initializeContractSnapshotFromReadinessPackageRequest: InitializeContractSnapshotFromReadinessPackageRequest;
}

export interface ContractReadinessControllerInitializeReceivablePlanRequestParams {
    id: string;
    initializeReceivablePlanFromReadinessPackageRequest: InitializeReceivablePlanFromReadinessPackageRequest;
}

export interface ContractReadinessControllerReviewDiffRequestParams {
    id: string;
    reviewCommercialReleaseBaselineDiffRequest: ReviewCommercialReleaseBaselineDiffRequest;
}


@Injectable({
  providedIn: 'root'
})
export class ContractReadinessApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: PomsApiConfiguration) {
        super(basePath, configuration);
    }

    /**
     * 创建商业放行基线与当前差异结果
     * @endpoint post /api/commercial-release-baselines
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerCreateCommercialReleaseBaseline(requestParameters: ContractReadinessControllerCreateCommercialReleaseBaselineRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CommercialReleaseBaselineSummary>;
    public contractReadinessControllerCreateCommercialReleaseBaseline(requestParameters: ContractReadinessControllerCreateCommercialReleaseBaselineRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CommercialReleaseBaselineSummary>>;
    public contractReadinessControllerCreateCommercialReleaseBaseline(requestParameters: ContractReadinessControllerCreateCommercialReleaseBaselineRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CommercialReleaseBaselineSummary>>;
    public contractReadinessControllerCreateCommercialReleaseBaseline(requestParameters: ContractReadinessControllerCreateCommercialReleaseBaselineRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const createCommercialReleaseBaselineRequest = requestParameters?.createCommercialReleaseBaselineRequest;
        if (createCommercialReleaseBaselineRequest === null || createCommercialReleaseBaselineRequest === undefined) {
            throw new Error('Required parameter createCommercialReleaseBaselineRequest was null or undefined when calling contractReadinessControllerCreateCommercialReleaseBaseline.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commercial-release-baselines`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CommercialReleaseBaselineSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createCommercialReleaseBaselineRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 创建签约就绪承接包
     * @endpoint post /api/contract-readiness-packages
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerCreateContractReadinessPackage(requestParameters: ContractReadinessControllerCreateContractReadinessPackageRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractReadinessDetail>;
    public contractReadinessControllerCreateContractReadinessPackage(requestParameters: ContractReadinessControllerCreateContractReadinessPackageRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractReadinessDetail>>;
    public contractReadinessControllerCreateContractReadinessPackage(requestParameters: ContractReadinessControllerCreateContractReadinessPackageRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractReadinessDetail>>;
    public contractReadinessControllerCreateContractReadinessPackage(requestParameters: ContractReadinessControllerCreateContractReadinessPackageRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const createContractReadinessPackageRequest = requestParameters?.createContractReadinessPackageRequest;
        if (createContractReadinessPackageRequest === null || createContractReadinessPackageRequest === undefined) {
            throw new Error('Required parameter createContractReadinessPackageRequest was null or undefined when calling contractReadinessControllerCreateContractReadinessPackage.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/contract-readiness-packages`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractReadinessDetail>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createContractReadinessPackageRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取商业放行基线详情
     * @endpoint get /api/commercial-release-baselines/{id}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerGetCommercialReleaseBaseline(requestParameters: ContractReadinessControllerGetCommercialReleaseBaselineRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CommercialReleaseBaselineSummary>;
    public contractReadinessControllerGetCommercialReleaseBaseline(requestParameters: ContractReadinessControllerGetCommercialReleaseBaselineRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CommercialReleaseBaselineSummary>>;
    public contractReadinessControllerGetCommercialReleaseBaseline(requestParameters: ContractReadinessControllerGetCommercialReleaseBaselineRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CommercialReleaseBaselineSummary>>;
    public contractReadinessControllerGetCommercialReleaseBaseline(requestParameters: ContractReadinessControllerGetCommercialReleaseBaselineRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contractReadinessControllerGetCommercialReleaseBaseline.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commercial-release-baselines/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CommercialReleaseBaselineSummary>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取签约就绪承接详情
     * @endpoint get /api/contract-readiness-packages/{id}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerGetContractReadinessPackage(requestParameters: ContractReadinessControllerGetContractReadinessPackageRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractReadinessDetail>;
    public contractReadinessControllerGetContractReadinessPackage(requestParameters: ContractReadinessControllerGetContractReadinessPackageRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractReadinessDetail>>;
    public contractReadinessControllerGetContractReadinessPackage(requestParameters: ContractReadinessControllerGetContractReadinessPackageRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractReadinessDetail>>;
    public contractReadinessControllerGetContractReadinessPackage(requestParameters: ContractReadinessControllerGetContractReadinessPackageRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contractReadinessControllerGetContractReadinessPackage.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/contract-readiness-packages/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractReadinessDetail>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取项目当前签约就绪承接包
     * @endpoint get /api/projects/{projectId}/contract-readiness
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerGetCurrentContractReadiness(requestParameters: ContractReadinessControllerGetCurrentContractReadinessRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractReadinessDetail>;
    public contractReadinessControllerGetCurrentContractReadiness(requestParameters: ContractReadinessControllerGetCurrentContractReadinessRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractReadinessDetail>>;
    public contractReadinessControllerGetCurrentContractReadiness(requestParameters: ContractReadinessControllerGetCurrentContractReadinessRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractReadinessDetail>>;
    public contractReadinessControllerGetCurrentContractReadiness(requestParameters: ContractReadinessControllerGetCurrentContractReadinessRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const projectId = requestParameters?.projectId;
        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling contractReadinessControllerGetCurrentContractReadiness.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/projects/${this.configuration.encodeParam({name: "projectId", value: projectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/contract-readiness`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractReadinessDetail>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取商业放行差异复核历史
     * @endpoint get /api/commercial-release-baselines/{id}/diff-history
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerGetDiffHistory(requestParameters: ContractReadinessControllerGetDiffHistoryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractDiffReviewHistoryView>;
    public contractReadinessControllerGetDiffHistory(requestParameters: ContractReadinessControllerGetDiffHistoryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractDiffReviewHistoryView>>;
    public contractReadinessControllerGetDiffHistory(requestParameters: ContractReadinessControllerGetDiffHistoryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractDiffReviewHistoryView>>;
    public contractReadinessControllerGetDiffHistory(requestParameters: ContractReadinessControllerGetDiffHistoryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contractReadinessControllerGetDiffHistory.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commercial-release-baselines/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/diff-history`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractDiffReviewHistoryView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 基于承接包初始化合同条款快照引用
     * @endpoint post /api/contract-readiness-packages/{id}:initializeContractSnapshot
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerInitializeContractSnapshot(requestParameters: ContractReadinessControllerInitializeContractSnapshotRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ReadinessInitializationResult>;
    public contractReadinessControllerInitializeContractSnapshot(requestParameters: ContractReadinessControllerInitializeContractSnapshotRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ReadinessInitializationResult>>;
    public contractReadinessControllerInitializeContractSnapshot(requestParameters: ContractReadinessControllerInitializeContractSnapshotRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ReadinessInitializationResult>>;
    public contractReadinessControllerInitializeContractSnapshot(requestParameters: ContractReadinessControllerInitializeContractSnapshotRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contractReadinessControllerInitializeContractSnapshot.');
        }
        const initializeContractSnapshotFromReadinessPackageRequest = requestParameters?.initializeContractSnapshotFromReadinessPackageRequest;
        if (initializeContractSnapshotFromReadinessPackageRequest === null || initializeContractSnapshotFromReadinessPackageRequest === undefined) {
            throw new Error('Required parameter initializeContractSnapshotFromReadinessPackageRequest was null or undefined when calling contractReadinessControllerInitializeContractSnapshot.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/contract-readiness-packages/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:initializeContractSnapshot`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ReadinessInitializationResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: initializeContractSnapshotFromReadinessPackageRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 基于承接包初始化应收计划引用
     * @endpoint post /api/contract-readiness-packages/{id}:initializeReceivablePlan
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerInitializeReceivablePlan(requestParameters: ContractReadinessControllerInitializeReceivablePlanRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ReadinessInitializationResult>;
    public contractReadinessControllerInitializeReceivablePlan(requestParameters: ContractReadinessControllerInitializeReceivablePlanRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ReadinessInitializationResult>>;
    public contractReadinessControllerInitializeReceivablePlan(requestParameters: ContractReadinessControllerInitializeReceivablePlanRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ReadinessInitializationResult>>;
    public contractReadinessControllerInitializeReceivablePlan(requestParameters: ContractReadinessControllerInitializeReceivablePlanRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contractReadinessControllerInitializeReceivablePlan.');
        }
        const initializeReceivablePlanFromReadinessPackageRequest = requestParameters?.initializeReceivablePlanFromReadinessPackageRequest;
        if (initializeReceivablePlanFromReadinessPackageRequest === null || initializeReceivablePlanFromReadinessPackageRequest === undefined) {
            throw new Error('Required parameter initializeReceivablePlanFromReadinessPackageRequest was null or undefined when calling contractReadinessControllerInitializeReceivablePlan.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/contract-readiness-packages/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:initializeReceivablePlan`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ReadinessInitializationResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: initializeReceivablePlanFromReadinessPackageRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 复核商业放行差异结果
     * @endpoint post /api/commercial-release-baselines/{id}:reviewDiff
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public contractReadinessControllerReviewDiff(requestParameters: ContractReadinessControllerReviewDiffRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CommercialDiffReviewResult>;
    public contractReadinessControllerReviewDiff(requestParameters: ContractReadinessControllerReviewDiffRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CommercialDiffReviewResult>>;
    public contractReadinessControllerReviewDiff(requestParameters: ContractReadinessControllerReviewDiffRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CommercialDiffReviewResult>>;
    public contractReadinessControllerReviewDiff(requestParameters: ContractReadinessControllerReviewDiffRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contractReadinessControllerReviewDiff.');
        }
        const reviewCommercialReleaseBaselineDiffRequest = requestParameters?.reviewCommercialReleaseBaselineDiffRequest;
        if (reviewCommercialReleaseBaselineDiffRequest === null || reviewCommercialReleaseBaselineDiffRequest === undefined) {
            throw new Error('Required parameter reviewCommercialReleaseBaselineDiffRequest was null or undefined when calling contractReadinessControllerReviewDiff.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/commercial-release-baselines/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:reviewDiff`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CommercialDiffReviewResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: reviewCommercialReleaseBaselineDiffRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
