/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ApproveLeadScoreOverrideRequest } from '../model/approve-lead-score-override-request';
// @ts-ignore
import { AssignLeadOwnerRequest } from '../model/assign-lead-owner-request';
// @ts-ignore
import { ClaimLeadOwnerRequest } from '../model/claim-lead-owner-request';
// @ts-ignore
import { CloseLeadRequest } from '../model/close-lead-request';
// @ts-ignore
import { ConvertLeadToProjectRequest } from '../model/convert-lead-to-project-request';
// @ts-ignore
import { CreateLeadRequest } from '../model/create-lead-request';
// @ts-ignore
import { LeadBudgetStatus } from '../model/lead-budget-status';
// @ts-ignore
import { LeadDetailView } from '../model/lead-detail-view';
// @ts-ignore
import { LeadListResponse } from '../model/lead-list-response';
// @ts-ignore
import { LeadOwnerAssignmentResult } from '../model/lead-owner-assignment-result';
// @ts-ignore
import { LeadOwnershipScope } from '../model/lead-ownership-scope';
// @ts-ignore
import { LeadRating } from '../model/lead-rating';
// @ts-ignore
import { LeadScoreHistoryView } from '../model/lead-score-history-view';
// @ts-ignore
import { LeadScoreOverrideSummary } from '../model/lead-score-override-summary';
// @ts-ignore
import { LeadSummary } from '../model/lead-summary';
// @ts-ignore
import { LeadUrgency } from '../model/lead-urgency';
// @ts-ignore
import { LeadWorkbenchScope } from '../model/lead-workbench-scope';
// @ts-ignore
import { ProjectSummary } from '../model/project-summary';
// @ts-ignore
import { QualifyLeadRequest } from '../model/qualify-lead-request';
// @ts-ignore
import { RejectLeadScoreOverrideRequest } from '../model/reject-lead-score-override-request';
// @ts-ignore
import { RevokeLeadScoreOverrideRequest } from '../model/revoke-lead-score-override-request';
// @ts-ignore
import { SubmitLeadScoreOverrideRequest } from '../model/submit-lead-score-override-request';
// @ts-ignore
import { UpdateLeadRequest } from '../model/update-lead-request';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { PomsApiConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface LeadControllerAssignOwnerRequestParams {
    id: string;
    assignLeadOwnerRequest: AssignLeadOwnerRequest;
}

export interface LeadControllerClaimOwnerRequestParams {
    id: string;
    claimLeadOwnerRequest: ClaimLeadOwnerRequest;
}

export interface LeadControllerCloseRequestParams {
    id: string;
    closeLeadRequest: CloseLeadRequest;
}

export interface LeadControllerConvertToProjectRequestParams {
    id: string;
    convertLeadToProjectRequest: ConvertLeadToProjectRequest;
}

export interface LeadControllerCreateRequestParams {
    createLeadRequest: CreateLeadRequest;
}

export interface LeadControllerGetByIdRequestParams {
    id: string;
}

export interface LeadControllerGetScoreHistoryRequestParams {
    id: string;
}

export interface LeadControllerListRequestParams {
    scope?: LeadWorkbenchScope;
    sourceCode?: string;
    budgetStatus?: LeadBudgetStatus;
    urgency?: LeadUrgency;
    rating?: LeadRating;
    ownerOrgId?: string;
    ownerUserId?: string;
    ownershipScope?: LeadOwnershipScope;
    keyword?: string;
    page?: number;
    pageSize?: number;
}

export interface LeadControllerQualifyRequestParams {
    id: string;
    qualifyLeadRequest: QualifyLeadRequest;
}

export interface LeadControllerSubmitScoreOverrideRequestParams {
    id: string;
    submitLeadScoreOverrideRequest: SubmitLeadScoreOverrideRequest;
}

export interface LeadControllerUpdateRequestParams {
    id: string;
    updateLeadRequest: UpdateLeadRequest;
}

export interface LeadScoreOverrideControllerApproveRequestParams {
    id: string;
    approveLeadScoreOverrideRequest: ApproveLeadScoreOverrideRequest;
}

export interface LeadScoreOverrideControllerRejectRequestParams {
    id: string;
    rejectLeadScoreOverrideRequest: RejectLeadScoreOverrideRequest;
}

export interface LeadScoreOverrideControllerRevokeRequestParams {
    id: string;
    revokeLeadScoreOverrideRequest: RevokeLeadScoreOverrideRequest;
}


@Injectable({
  providedIn: 'root'
})
export class LeadApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: PomsApiConfiguration) {
        super(basePath, configuration);
    }

    /**
     * 分配或改派线索销售主责
     * @endpoint post /api/leads/{id}:assignOwner
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerAssignOwner(requestParameters: LeadControllerAssignOwnerRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadOwnerAssignmentResult>;
    public leadControllerAssignOwner(requestParameters: LeadControllerAssignOwnerRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadOwnerAssignmentResult>>;
    public leadControllerAssignOwner(requestParameters: LeadControllerAssignOwnerRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadOwnerAssignmentResult>>;
    public leadControllerAssignOwner(requestParameters: LeadControllerAssignOwnerRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerAssignOwner.');
        }
        const assignLeadOwnerRequest = requestParameters?.assignLeadOwnerRequest;
        if (assignLeadOwnerRequest === null || assignLeadOwnerRequest === undefined) {
            throw new Error('Required parameter assignLeadOwnerRequest was null or undefined when calling leadControllerAssignOwner.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:assignOwner`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadOwnerAssignmentResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: assignLeadOwnerRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 申领公共池线索
     * @endpoint post /api/leads/{id}:claim
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerClaimOwner(requestParameters: LeadControllerClaimOwnerRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadOwnerAssignmentResult>;
    public leadControllerClaimOwner(requestParameters: LeadControllerClaimOwnerRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadOwnerAssignmentResult>>;
    public leadControllerClaimOwner(requestParameters: LeadControllerClaimOwnerRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadOwnerAssignmentResult>>;
    public leadControllerClaimOwner(requestParameters: LeadControllerClaimOwnerRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerClaimOwner.');
        }
        const claimLeadOwnerRequest = requestParameters?.claimLeadOwnerRequest;
        if (claimLeadOwnerRequest === null || claimLeadOwnerRequest === undefined) {
            throw new Error('Required parameter claimLeadOwnerRequest was null or undefined when calling leadControllerClaimOwner.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:claim`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadOwnerAssignmentResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: claimLeadOwnerRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 关闭线索
     * @endpoint post /api/leads/{id}:close
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerClose(requestParameters: LeadControllerCloseRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadSummary>;
    public leadControllerClose(requestParameters: LeadControllerCloseRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadSummary>>;
    public leadControllerClose(requestParameters: LeadControllerCloseRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadSummary>>;
    public leadControllerClose(requestParameters: LeadControllerCloseRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerClose.');
        }
        const closeLeadRequest = requestParameters?.closeLeadRequest;
        if (closeLeadRequest === null || closeLeadRequest === undefined) {
            throw new Error('Required parameter closeLeadRequest was null or undefined when calling leadControllerClose.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:close`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: closeLeadRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 将有效线索转为项目
     * @endpoint post /api/leads/{id}:convertToProject
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerConvertToProject(requestParameters: LeadControllerConvertToProjectRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ProjectSummary>;
    public leadControllerConvertToProject(requestParameters: LeadControllerConvertToProjectRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ProjectSummary>>;
    public leadControllerConvertToProject(requestParameters: LeadControllerConvertToProjectRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ProjectSummary>>;
    public leadControllerConvertToProject(requestParameters: LeadControllerConvertToProjectRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerConvertToProject.');
        }
        const convertLeadToProjectRequest = requestParameters?.convertLeadToProjectRequest;
        if (convertLeadToProjectRequest === null || convertLeadToProjectRequest === undefined) {
            throw new Error('Required parameter convertLeadToProjectRequest was null or undefined when calling leadControllerConvertToProject.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:convertToProject`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ProjectSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: convertLeadToProjectRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 登记线索
     * @endpoint post /api/leads
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerCreate(requestParameters: LeadControllerCreateRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadSummary>;
    public leadControllerCreate(requestParameters: LeadControllerCreateRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadSummary>>;
    public leadControllerCreate(requestParameters: LeadControllerCreateRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadSummary>>;
    public leadControllerCreate(requestParameters: LeadControllerCreateRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const createLeadRequest = requestParameters?.createLeadRequest;
        if (createLeadRequest === null || createLeadRequest === undefined) {
            throw new Error('Required parameter createLeadRequest was null or undefined when calling leadControllerCreate.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createLeadRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取线索详情
     * @endpoint get /api/leads/{id}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerGetById(requestParameters: LeadControllerGetByIdRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadDetailView>;
    public leadControllerGetById(requestParameters: LeadControllerGetByIdRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadDetailView>>;
    public leadControllerGetById(requestParameters: LeadControllerGetByIdRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadDetailView>>;
    public leadControllerGetById(requestParameters: LeadControllerGetByIdRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerGetById.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadDetailView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取线索评分历史与人工覆盖状态
     * @endpoint get /api/leads/{id}/score-history
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerGetScoreHistory(requestParameters: LeadControllerGetScoreHistoryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadScoreHistoryView>;
    public leadControllerGetScoreHistory(requestParameters: LeadControllerGetScoreHistoryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadScoreHistoryView>>;
    public leadControllerGetScoreHistory(requestParameters: LeadControllerGetScoreHistoryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadScoreHistoryView>>;
    public leadControllerGetScoreHistory(requestParameters: LeadControllerGetScoreHistoryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerGetScoreHistory.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/score-history`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadScoreHistoryView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取线索列表
     * @endpoint get /api/leads
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerList(requestParameters?: LeadControllerListRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadListResponse>;
    public leadControllerList(requestParameters?: LeadControllerListRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadListResponse>>;
    public leadControllerList(requestParameters?: LeadControllerListRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadListResponse>>;
    public leadControllerList(requestParameters?: LeadControllerListRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const scope = requestParameters?.scope;
        const sourceCode = requestParameters?.sourceCode;
        const budgetStatus = requestParameters?.budgetStatus;
        const urgency = requestParameters?.urgency;
        const rating = requestParameters?.rating;
        const ownerOrgId = requestParameters?.ownerOrgId;
        const ownerUserId = requestParameters?.ownerUserId;
        const ownershipScope = requestParameters?.ownershipScope;
        const keyword = requestParameters?.keyword;
        const page = requestParameters?.page;
        const pageSize = requestParameters?.pageSize;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'scope',
            <any>scope,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sourceCode',
            <any>sourceCode,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'budgetStatus',
            <any>budgetStatus,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'urgency',
            <any>urgency,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'rating',
            <any>rating,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'ownerOrgId',
            <any>ownerOrgId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'ownerUserId',
            <any>ownerUserId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'ownershipScope',
            <any>ownershipScope,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'keyword',
            <any>keyword,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'pageSize',
            <any>pageSize,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadListResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 确认线索有效
     * @endpoint post /api/leads/{id}:qualify
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerQualify(requestParameters: LeadControllerQualifyRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadSummary>;
    public leadControllerQualify(requestParameters: LeadControllerQualifyRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadSummary>>;
    public leadControllerQualify(requestParameters: LeadControllerQualifyRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadSummary>>;
    public leadControllerQualify(requestParameters: LeadControllerQualifyRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerQualify.');
        }
        const qualifyLeadRequest = requestParameters?.qualifyLeadRequest;
        if (qualifyLeadRequest === null || qualifyLeadRequest === undefined) {
            throw new Error('Required parameter qualifyLeadRequest was null or undefined when calling leadControllerQualify.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:qualify`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: qualifyLeadRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 提交线索评分人工覆盖申请
     * @endpoint post /api/leads/{id}/score-overrides
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerSubmitScoreOverride(requestParameters: LeadControllerSubmitScoreOverrideRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadScoreOverrideSummary>;
    public leadControllerSubmitScoreOverride(requestParameters: LeadControllerSubmitScoreOverrideRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadScoreOverrideSummary>>;
    public leadControllerSubmitScoreOverride(requestParameters: LeadControllerSubmitScoreOverrideRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadScoreOverrideSummary>>;
    public leadControllerSubmitScoreOverride(requestParameters: LeadControllerSubmitScoreOverrideRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerSubmitScoreOverride.');
        }
        const submitLeadScoreOverrideRequest = requestParameters?.submitLeadScoreOverrideRequest;
        if (submitLeadScoreOverrideRequest === null || submitLeadScoreOverrideRequest === undefined) {
            throw new Error('Required parameter submitLeadScoreOverrideRequest was null or undefined when calling leadControllerSubmitScoreOverride.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/score-overrides`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadScoreOverrideSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: submitLeadScoreOverrideRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 更新线索基础信息
     * @endpoint patch /api/leads/{id}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadControllerUpdate(requestParameters: LeadControllerUpdateRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadSummary>;
    public leadControllerUpdate(requestParameters: LeadControllerUpdateRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadSummary>>;
    public leadControllerUpdate(requestParameters: LeadControllerUpdateRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadSummary>>;
    public leadControllerUpdate(requestParameters: LeadControllerUpdateRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadControllerUpdate.');
        }
        const updateLeadRequest = requestParameters?.updateLeadRequest;
        if (updateLeadRequest === null || updateLeadRequest === undefined) {
            throw new Error('Required parameter updateLeadRequest was null or undefined when calling leadControllerUpdate.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/leads/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadSummary>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: updateLeadRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 批准线索评分人工覆盖
     * @endpoint post /api/lead-score-overrides/{id}:approve
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadScoreOverrideControllerApprove(requestParameters: LeadScoreOverrideControllerApproveRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadScoreOverrideSummary>;
    public leadScoreOverrideControllerApprove(requestParameters: LeadScoreOverrideControllerApproveRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadScoreOverrideSummary>>;
    public leadScoreOverrideControllerApprove(requestParameters: LeadScoreOverrideControllerApproveRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadScoreOverrideSummary>>;
    public leadScoreOverrideControllerApprove(requestParameters: LeadScoreOverrideControllerApproveRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadScoreOverrideControllerApprove.');
        }
        const approveLeadScoreOverrideRequest = requestParameters?.approveLeadScoreOverrideRequest;
        if (approveLeadScoreOverrideRequest === null || approveLeadScoreOverrideRequest === undefined) {
            throw new Error('Required parameter approveLeadScoreOverrideRequest was null or undefined when calling leadScoreOverrideControllerApprove.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/lead-score-overrides/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:approve`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadScoreOverrideSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: approveLeadScoreOverrideRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 驳回线索评分人工覆盖
     * @endpoint post /api/lead-score-overrides/{id}:reject
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadScoreOverrideControllerReject(requestParameters: LeadScoreOverrideControllerRejectRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadScoreOverrideSummary>;
    public leadScoreOverrideControllerReject(requestParameters: LeadScoreOverrideControllerRejectRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadScoreOverrideSummary>>;
    public leadScoreOverrideControllerReject(requestParameters: LeadScoreOverrideControllerRejectRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadScoreOverrideSummary>>;
    public leadScoreOverrideControllerReject(requestParameters: LeadScoreOverrideControllerRejectRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadScoreOverrideControllerReject.');
        }
        const rejectLeadScoreOverrideRequest = requestParameters?.rejectLeadScoreOverrideRequest;
        if (rejectLeadScoreOverrideRequest === null || rejectLeadScoreOverrideRequest === undefined) {
            throw new Error('Required parameter rejectLeadScoreOverrideRequest was null or undefined when calling leadScoreOverrideControllerReject.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/lead-score-overrides/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:reject`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadScoreOverrideSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: rejectLeadScoreOverrideRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 撤销线索评分人工覆盖
     * @endpoint post /api/lead-score-overrides/{id}:revoke
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public leadScoreOverrideControllerRevoke(requestParameters: LeadScoreOverrideControllerRevokeRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LeadScoreOverrideSummary>;
    public leadScoreOverrideControllerRevoke(requestParameters: LeadScoreOverrideControllerRevokeRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LeadScoreOverrideSummary>>;
    public leadScoreOverrideControllerRevoke(requestParameters: LeadScoreOverrideControllerRevokeRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LeadScoreOverrideSummary>>;
    public leadScoreOverrideControllerRevoke(requestParameters: LeadScoreOverrideControllerRevokeRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling leadScoreOverrideControllerRevoke.');
        }
        const revokeLeadScoreOverrideRequest = requestParameters?.revokeLeadScoreOverrideRequest;
        if (revokeLeadScoreOverrideRequest === null || revokeLeadScoreOverrideRequest === undefined) {
            throw new Error('Required parameter revokeLeadScoreOverrideRequest was null or undefined when calling leadScoreOverrideControllerRevoke.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (pomsSession) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/lead-score-overrides/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:revoke`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LeadScoreOverrideSummary>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: revokeLeadScoreOverrideRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
