/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ConfirmProjectHandoverRequest } from '../model/confirm-project-handover-request';
// @ts-ignore
import { ConfirmProjectHandoverResult } from '../model/confirm-project-handover-result';
// @ts-ignore
import { ContractHandoverSummaryView } from '../model/contract-handover-summary-view';
// @ts-ignore
import { ProjectHandoverDetailView } from '../model/project-handover-detail-view';
// @ts-ignore
import { RebaselineContractHandoverRequest } from '../model/rebaseline-contract-handover-request';
// @ts-ignore
import { RebaselineContractHandoverResult } from '../model/rebaseline-contract-handover-result';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { PomsApiConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface ProjectHandoverControllerConfirmProjectHandoverRequestParams {
    handoverId: string;
    confirmProjectHandoverRequest: ConfirmProjectHandoverRequest;
}

export interface ProjectHandoverControllerGetContractHandoverSummaryRequestParams {
    projectId: string;
}

export interface ProjectHandoverControllerGetProjectHandoverDetailByHandoverRequestParams {
    handoverId: string;
}

export interface ProjectHandoverControllerGetProjectHandoverDetailByProjectRequestParams {
    projectId: string;
}

export interface ProjectHandoverControllerRebaselineContractHandoverRequestParams {
    rebaselineContractHandoverRequest: RebaselineContractHandoverRequest;
}


@Injectable({
  providedIn: 'root'
})
export class ProjectHandoverApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: PomsApiConfiguration) {
        super(basePath, configuration);
    }

    /**
     * 确认项目移交
     * @endpoint post /api/project-handovers/{handoverId}:confirm
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public projectHandoverControllerConfirmProjectHandover(requestParameters: ProjectHandoverControllerConfirmProjectHandoverRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ConfirmProjectHandoverResult>;
    public projectHandoverControllerConfirmProjectHandover(requestParameters: ProjectHandoverControllerConfirmProjectHandoverRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ConfirmProjectHandoverResult>>;
    public projectHandoverControllerConfirmProjectHandover(requestParameters: ProjectHandoverControllerConfirmProjectHandoverRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ConfirmProjectHandoverResult>>;
    public projectHandoverControllerConfirmProjectHandover(requestParameters: ProjectHandoverControllerConfirmProjectHandoverRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const handoverId = requestParameters?.handoverId;
        if (handoverId === null || handoverId === undefined) {
            throw new Error('Required parameter handoverId was null or undefined when calling projectHandoverControllerConfirmProjectHandover.');
        }
        const confirmProjectHandoverRequest = requestParameters?.confirmProjectHandoverRequest;
        if (confirmProjectHandoverRequest === null || confirmProjectHandoverRequest === undefined) {
            throw new Error('Required parameter confirmProjectHandoverRequest was null or undefined when calling projectHandoverControllerConfirmProjectHandover.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/project-handovers/${this.configuration.encodeParam({name: "handoverId", value: handoverId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}:confirm`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ConfirmProjectHandoverResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: confirmProjectHandoverRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取项目合同承接摘要
     * @endpoint get /api/projects/{projectId}/contract-handover
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public projectHandoverControllerGetContractHandoverSummary(requestParameters: ProjectHandoverControllerGetContractHandoverSummaryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ContractHandoverSummaryView>;
    public projectHandoverControllerGetContractHandoverSummary(requestParameters: ProjectHandoverControllerGetContractHandoverSummaryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ContractHandoverSummaryView>>;
    public projectHandoverControllerGetContractHandoverSummary(requestParameters: ProjectHandoverControllerGetContractHandoverSummaryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ContractHandoverSummaryView>>;
    public projectHandoverControllerGetContractHandoverSummary(requestParameters: ProjectHandoverControllerGetContractHandoverSummaryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const projectId = requestParameters?.projectId;
        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling projectHandoverControllerGetContractHandoverSummary.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/projects/${this.configuration.encodeParam({name: "projectId", value: projectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/contract-handover`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ContractHandoverSummaryView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取指定移交详情
     * @endpoint get /api/project-handovers/{handoverId}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public projectHandoverControllerGetProjectHandoverDetailByHandover(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByHandoverRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ProjectHandoverDetailView>;
    public projectHandoverControllerGetProjectHandoverDetailByHandover(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByHandoverRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ProjectHandoverDetailView>>;
    public projectHandoverControllerGetProjectHandoverDetailByHandover(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByHandoverRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ProjectHandoverDetailView>>;
    public projectHandoverControllerGetProjectHandoverDetailByHandover(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByHandoverRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const handoverId = requestParameters?.handoverId;
        if (handoverId === null || handoverId === undefined) {
            throw new Error('Required parameter handoverId was null or undefined when calling projectHandoverControllerGetProjectHandoverDetailByHandover.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/project-handovers/${this.configuration.encodeParam({name: "handoverId", value: handoverId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ProjectHandoverDetailView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取项目最新移交详情
     * @endpoint get /api/projects/{projectId}/project-handover
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public projectHandoverControllerGetProjectHandoverDetailByProject(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByProjectRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ProjectHandoverDetailView>;
    public projectHandoverControllerGetProjectHandoverDetailByProject(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByProjectRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ProjectHandoverDetailView>>;
    public projectHandoverControllerGetProjectHandoverDetailByProject(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByProjectRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ProjectHandoverDetailView>>;
    public projectHandoverControllerGetProjectHandoverDetailByProject(requestParameters: ProjectHandoverControllerGetProjectHandoverDetailByProjectRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const projectId = requestParameters?.projectId;
        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling projectHandoverControllerGetProjectHandoverDetailByProject.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/projects/${this.configuration.encodeParam({name: "projectId", value: projectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/project-handover`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ProjectHandoverDetailView>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 发起合同移交前再基线化
     * @endpoint post /api/contract-handover-rebaselines
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public projectHandoverControllerRebaselineContractHandover(requestParameters: ProjectHandoverControllerRebaselineContractHandoverRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<RebaselineContractHandoverResult>;
    public projectHandoverControllerRebaselineContractHandover(requestParameters: ProjectHandoverControllerRebaselineContractHandoverRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<RebaselineContractHandoverResult>>;
    public projectHandoverControllerRebaselineContractHandover(requestParameters: ProjectHandoverControllerRebaselineContractHandoverRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<RebaselineContractHandoverResult>>;
    public projectHandoverControllerRebaselineContractHandover(requestParameters: ProjectHandoverControllerRebaselineContractHandoverRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const rebaselineContractHandoverRequest = requestParameters?.rebaselineContractHandoverRequest;
        if (rebaselineContractHandoverRequest === null || rebaselineContractHandoverRequest === undefined) {
            throw new Error('Required parameter rebaselineContractHandoverRequest was null or undefined when calling projectHandoverControllerRebaselineContractHandover.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/contract-handover-rebaselines`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<RebaselineContractHandoverResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: rebaselineContractHandoverRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
