/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentTargetType } from './attachment-target-type';
import { AttachmentRelationType } from './attachment-relation-type';
import { AttachmentLinkStatus } from './attachment-link-status';


export interface AttachmentLinkSummary {
    id: string;
    attachmentId: string;
    targetType: AttachmentTargetType;
    targetId: string;
    relationType: AttachmentRelationType;
    status: AttachmentLinkStatus;
    linkedBy: string | null;
    linkedAt: string;
    unlinkedBy: string | null;
    unlinkedAt: string | null;
}
