/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum AttachmentUploadSessionStatus {

    Pending = 'pending',

    Uploading = 'uploading',

    Uploaded = 'uploaded',

    Validating = 'validating',

    Completed = 'completed',

    Failed = 'failed',

    Expired = 'expired',

    Aborted = 'aborted'
}
