/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentLinkSummary } from './attachment-link-summary';
import { AttachmentStatus } from './attachment-status';
import { AttachmentSecurityLevel } from './attachment-security-level';
import { AttachmentCategory } from './attachment-category';


export interface AttachmentSummary {
    id: string;
    originalName: string;
    displayName: string;
    extension: string;
    mimeType: string;
    sizeBytes: number;
    checksumSha256: string;
    category: AttachmentCategory;
    securityLevel: AttachmentSecurityLevel;
    status: AttachmentStatus;
    description: string | null;
    versionGroupId: string | null;
    versionNo: number;
    isLatest: boolean;
    isFinal: boolean;
    uploadedBy: string | null;
    uploadedByName: string | null;
    uploadedAt: string;
    updatedAt: string;
    deletedAt: string | null;
    links: Array<AttachmentLinkSummary>;
}
