/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum AttachmentTargetType {

    Lead = 'lead',

    Customer = 'customer',

    Project = 'project',

    Contract = 'contract',

    SalesFollowUp = 'sales-follow-up'
}
