/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum BusinessDomain {

    ContractFinance = 'contract-finance',

    Commission = 'commission',

    Sales = 'sales',

    ProjectHandover = 'project-handover'
}
