/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';
import { BaselineSelectionSource } from './baseline-selection-source';
import { CommissionRoleAssignmentSummary } from './commission-role-assignment-summary';


export interface CommissionFinalSettlementView {
    projectId: string;
    finalSettlementStatus: string;
    nonRetentionSettlementStatus: string;
    retentionSettlementStatus: string;
    retentionDueDate: string | null;
    retentionDueStatus: CommissionFinalSettlementViewRetentionDueStatusEnum;
    retentionRequirementSummary: string | null;
    retentionReceiptSummary: string | null;
    departureExceptionSummary: string | null;
    freezeVersionSummary: CommissionRoleAssignmentSummary;
    baselineSelectionSource: BaselineSelectionSource;
    taxImpactSummary: string;
    taxImpactPendingAmount: string;
    dataMaturityLevel: string;
    costActionRecommendation: OperatingSnapshotActionLevel;
    currentActionLevel: OperatingSnapshotActionLevel;
    referencedBaselineVersion: string;
    referencedSnapshotVersion: string;
    summaryPackageKey: string;
    summarySnapshotId: string;
    projectionLevel: string;
    exportPolicy: string;
    allowedActions: Array<string>;
}
export enum CommissionFinalSettlementViewRetentionDueStatusEnum {
    Missing = 'missing',
    Pending = 'pending',
    Due = 'due'
};
