/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommissionRoleAssignmentSummaryParticipantsJsonInner } from './commission-role-assignment-summary-participants-json-inner';


export interface CommissionRoleAssignmentSummary { 
    id: string;
    projectId: string;
    version: number;
    rowVersion: number;
    isCurrent: boolean;
    status: CommissionRoleAssignmentSummaryStatusEnum;
    participantsJson: Array<CommissionRoleAssignmentSummaryParticipantsJsonInner>;
    sourceHandoverId: string | null;
    sourceHandoverRebaselineRecordId: string | null;
    contractSummarySnapshotId: string | null;
    handoverSummarySnapshotId: string | null;
    effectiveHandoverBaselineSnapshotId: string | null;
    frozenAt: string | null;
    createdAt: string;
    updatedAt: string;
}
export enum CommissionRoleAssignmentSummaryStatusEnum {
    Draft = 'draft',
    Frozen = 'frozen',
    Superseded = 'superseded'
};



