/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommercialBaselineReviewDecision } from './commercial-baseline-review-decision';


export interface CommercialBaselineReviewRecordSummary { 
    id: string;
    baselineId: string;
    diffResultId: string;
    projectId: string;
    decision: CommercialBaselineReviewDecision;
    reviewedFieldKeys: Array<string>;
    comment: string | null;
    reviewerUserId: string;
    createdAt: string;
}



