/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum CommissionRuleExplanationGateDecision {

    AllowFinalSettlement = 'ALLOW_FINAL_SETTLEMENT',

    SettledRetention = 'SETTLED_RETENTION',

    BlockRetention = 'BLOCK_RETENTION',

    ReviewRetention = 'REVIEW_RETENTION',

    AllowRetention = 'ALLOW_RETENTION'
}
