/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum CommercialDiffReviewStatus {

    NotRequired = 'not-required',

    PendingReview = 'pending-review',

    Approved = 'approved',

    Rejected = 'rejected'
}
