/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum CommissionAdjustmentStatus {

    Draft = 'draft',

    PendingApproval = 'pending-approval',

    Approved = 'approved',

    Executed = 'executed',

    Rejected = 'rejected',

    Closed = 'closed'
}
