/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum CommissionPayoutStatus {

    Draft = 'draft',

    PendingApproval = 'pending-approval',

    Approved = 'approved',

    Paid = 'paid',

    Suspended = 'suspended',

    Reversed = 'reversed'
}
