/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum CompetitorPosition {

    Incumbent = 'incumbent',

    ActiveCompetitor = 'active-competitor',

    PotentialCompetitor = 'potential-competitor',

    Unknown = 'unknown'
}
