/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmSharedCostAllocationBasisRequestProjectShareItemsInner {
    projectId: string;
    allocatedAmount: string;
    allocationRatio?: string | null;
    allocationSummary?: string | null;
}
