/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmCostStageAttributionRequest { 
    stageAttributionMode: ConfirmCostStageAttributionRequestStageAttributionModeEnum;
    attributedStage: string;
    lockedBySnapshotId?: string | null;
    attributionSummary?: string | null;
    comment?: string | null;
    expectedVersion?: number;
}
export enum ConfirmCostStageAttributionRequestStageAttributionModeEnum {
    Auto = 'auto',
    Manual = 'manual'
};



