/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensitiveStringFieldProjection } from './sensitive-string-field-projection';


export interface ContractTermSnapshotSummary {
    id: string;
    contractId: string;
    effectiveAt: string;
    effectiveBy: string | null;
    retentionDueDate: string | null;
    amountTaxInclusiveProjection: SensitiveStringFieldProjection;
    amountTaxExclusiveProjection: SensitiveStringFieldProjection;
    taxRateProjection: SensitiveStringFieldProjection;
    downPaymentRateProjection: SensitiveStringFieldProjection;
    retentionRateProjection: SensitiveStringFieldProjection;
    paymentTermsProjection: SensitiveStringFieldProjection;
    sourceReadinessId: string | null;
    sourceBaselineId: string | null;
    version: number;
    snapshotStatus: ContractTermSnapshotSummarySnapshotStatusEnum;
    createdAt: string;
    createdBy: string | null;
    rowVersion: number;
}
export enum ContractTermSnapshotSummarySnapshotStatusEnum {
    Active = 'active',
    Superseded = 'superseded',
    Voided = 'voided'
};
