/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractHandoverReceivablePlanInitStatus } from './contract-handover-receivable-plan-init-status';


export interface ContractHandoverReceivablePlanInitSummary {
    status: ContractHandoverReceivablePlanInitStatus;
    initializedReceivablePlanVersionId: string | null;
    receivablePlanInitializedAt: string | null;
    summary: string;
}
