/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractStatus } from './contract-status';


export interface ContractHandoverContractItemSummary { 
    id: string;
    contractNo: string;
    status: ContractStatus;
    signedAmount: string;
    currencyCode: string;
    currentSnapshotId: string | null;
    signedAt: string | null;
}



