/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractReadinessItemType } from './contract-readiness-item-type';
import { ContractReadinessItemStatus } from './contract-readiness-item-status';


export interface ContractReadinessItem { 
    id: string;
    itemType: ContractReadinessItemType;
    itemKey: string;
    label: string;
    summary: string | null;
    status: ContractReadinessItemStatus;
    responsibleRole: string | null;
    navigationHint: string | null;
    sortOrder: number;
}



