/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingLifecycleStatus } from './operating-lifecycle-status';
import { CostStageAttributionMode } from './cost-stage-attribution-mode';


export interface CostStageAttributionSnapshotSummary {
    id: string;
    costRecordId: string;
    attributedStage: string;
    attributionMode: CostStageAttributionMode;
    lockedBySnapshotId: string | null;
    attributionSummary: string | null;
    status: OperatingLifecycleStatus;
    supersedesId: string | null;
    handledAt: string | null;
    handledBy: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
}
