/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProjectCompletionRecordRequest {
    acceptanceRecordId: string;
    completionResult: CreateProjectCompletionRecordRequestCompletionResultEnum;
    completedAt: string;
    completionSummary: string;
    evidenceSummary: string;
}
export enum CreateProjectCompletionRecordRequestCompletionResultEnum {
    Completed = 'completed',
    ConditionalCompleted = 'conditional-completed'
};
