/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommissionRuleVersionSummaryTierDefinitionJson } from './commission-rule-version-summary-tier-definition-json';


export interface CreateCommissionRuleVersionRequest { 
    ruleCode: string;
    version: number;
    tierDefinitionJson: CommissionRuleVersionSummaryTierDefinitionJson;
    firstStageCapRuleJson?: { [key: string]: any; } | null;
    secondStageCapRuleJson?: { [key: string]: any; } | null;
    retentionRuleJson?: { [key: string]: any; } | null;
    lowDownPaymentRuleJson?: { [key: string]: any; } | null;
    exceptionRuleJson?: { [key: string]: any; } | null;
    effectiveFrom?: string | null;
}

