/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProcurementProjectActualCostRecordRequest {
    costType: CreateProcurementProjectActualCostRecordRequestCostTypeEnum;
    payableRecordId: string;
    costDescription?: string | null;
    evidenceSummary?: string | null;
    taxImpactSummary?: string | null;
    expectedSourceVersion?: number;
}
export enum CreateProcurementProjectActualCostRecordRequestCostTypeEnum {
    Procurement = 'procurement'
};
