/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProjectRequest { 
    projectCode: string;
    projectName: string;
    customerId?: string | null;
    status?: string;
    currentStage: string;
    ownerOrgId?: string | null;
    ownerUserId?: string | null;
    plannedSignAt?: string | null;
    createdBy?: string | null;
    updatedBy?: string | null;
}

