/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCustomerRequest {
    displayName: string;
    legalName?: string | null;
    shortName?: string | null;
    ownerOrgId?: string | null;
    ownerUserId?: string | null;
    sourceChannel?: string | null;
    remark?: string | null;
}
