/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LaborCostPeriodType } from './labor-cost-period-type';


export interface CreateLaborProjectActualCostRecordRequest {
    costType: CreateLaborProjectActualCostRecordRequestCostTypeEnum;
    laborPersonId?: string | null;
    laborRole?: string | null;
    laborPeriodType: LaborCostPeriodType;
    laborPeriodStart: string;
    laborPeriodEnd: string;
    actualHours?: string | null;
    actualPersonDays?: string | null;
    workSummary?: string | null;
    rateVersionId: string;
    costDescription?: string | null;
    attachmentIds?: Array<string>;
}
export enum CreateLaborProjectActualCostRecordRequestCostTypeEnum {
    Labor = 'LABOR'
};
