/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalOrgProvider } from './external-org-provider';


export interface CreateExternalOrgSourceRequest {
    provider: ExternalOrgProvider;
    externalTenantId?: string | null;
    displayName: string;
    providerConfigId?: string | null;
    authoritativeOrgUnitId?: string | null;
    externalRootDepartmentId?: string | null;
    syncScopes?: Array<string>;
}
