/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LaborCostPeriodType } from './labor-cost-period-type';
import { CreateExpenseProjectActualCostRecordRequest } from './create-expense-project-actual-cost-record-request';
import { CreateLaborProjectActualCostRecordRequest } from './create-labor-project-actual-cost-record-request';
import { CreatePaymentFactProjectActualCostRecordRequest } from './create-payment-fact-project-actual-cost-record-request';
import { CreateInvoiceProjectActualCostRecordRequest } from './create-invoice-project-actual-cost-record-request';
import { CreateProcurementProjectActualCostRecordRequest } from './create-procurement-project-actual-cost-record-request';


/**
 * @type CreateProjectActualCostRecordRequest
 * @export
 */
export type CreateProjectActualCostRecordRequest = CreateExpenseProjectActualCostRecordRequest | CreateInvoiceProjectActualCostRecordRequest | CreateLaborProjectActualCostRecordRequest | CreatePaymentFactProjectActualCostRecordRequest | CreateProcurementProjectActualCostRecordRequest;
