/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePlatformUserRequest { 
    username: string;
    displayName: string;
    email?: string | null;
    phone?: string | null;
    primaryOrgUnitId: string | null;
    initialRoleIds?: Array<string>;
}

