/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectBidCommercialMaterialItemInput } from './project-bid-commercial-material-item-input';
import { ProjectBidCommercialTimelineItemInput } from './project-bid-commercial-timeline-item-input';


export interface CreateProjectBidCommercialProcessRequest {
    bidMode: CreateProjectBidCommercialProcessRequestBidModeEnum;
    currentStage: CreateProjectBidCommercialProcessRequestCurrentStageEnum;
    decision: CreateProjectBidCommercialProcessRequestDecisionEnum;
    resultStatus: CreateProjectBidCommercialProcessRequestResultStatusEnum;
    processSummary: string;
    decisionSummary?: string | null;
    resultSummary?: string | null;
    tenderNo?: string | null;
    bidPackageNo?: string | null;
    ownerRole?: string | null;
    materialItems?: Array<ProjectBidCommercialMaterialItemInput>;
    timelineItems?: Array<ProjectBidCommercialTimelineItemInput>;
}
export enum CreateProjectBidCommercialProcessRequestBidModeEnum {
    PublicTender = 'public-tender',
    Invitation = 'invitation',
    Comparison = 'comparison',
    CommercialNegotiation = 'commercial-negotiation',
    CompetitiveNegotiation = 'competitive-negotiation',
    DirectCommercial = 'direct-commercial',
    NotRequired = 'not-required'
};
export enum CreateProjectBidCommercialProcessRequestCurrentStageEnum {
    NotStarted = 'not-started',
    Preparation = 'preparation',
    Submitted = 'submitted',
    Negotiating = 'negotiating',
    ResultConfirmed = 'result-confirmed',
    Closed = 'closed'
};
export enum CreateProjectBidCommercialProcessRequestDecisionEnum {
    Pending = 'pending',
    Participate = 'participate',
    NoBid = 'no-bid',
    NotRequired = 'not-required'
};
export enum CreateProjectBidCommercialProcessRequestResultStatusEnum {
    Pending = 'pending',
    Won = 'won',
    Lost = 'lost',
    Cancelled = 'cancelled',
    NotApplicable = 'not-applicable'
};
