/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SanitizedUserWithOrgUnits } from './sanitized-user-with-org-units';
import { AuthSessionCsrfHint } from './auth-session-csrf-hint';
import { CurrentAuthSessionStatus } from './current-auth-session-status';


export interface CurrentAuthSessionView {
    authenticated: boolean;
    status: CurrentAuthSessionStatus | null;
    user: SanitizedUserWithOrgUnits | null;
    permissions: Array<CurrentAuthSessionViewPermissionsEnum>;
    expiresAt: string | null;
    csrf: AuthSessionCsrfHint;
}
export enum CurrentAuthSessionViewPermissionsEnum {
    PlatformUsersManage = 'platform:users:manage',
    PlatformRolesManage = 'platform:roles:manage',
    PlatformNavigationManage = 'platform:navigation:manage',
    PlatformOrgUnitsManage = 'platform:org-units:manage',
    PlatformDictionariesManage = 'platform:dictionaries:manage',
    PlatformIdentityProvidersManage = 'platform:identity-providers:manage',
    PlatformAttachmentStorageProvidersManage = 'platform:attachment-storage-providers:manage',
    PlatformSystemSettingsManage = 'platform:system-settings:manage',
    CustomerRead = 'customer:read',
    CustomerWrite = 'customer:write',
    CommissionRuleVersionsManage = 'commission:rule-versions:manage',
    CommissionAssignmentsManage = 'commission:assignments:manage',
    CommissionCalculationsManage = 'commission:calculations:manage',
    CommissionPayoutsManage = 'commission:payouts:manage',
    CommissionAdjustmentsManage = 'commission:adjustments:manage',
    ContractFinanceManage = 'contract:finance:manage',
    ContractFinanceSensitiveRead = 'contract:finance:sensitive:read',
    OperatingFinanceSensitiveRead = 'operating:finance:sensitive:read',
    CommissionAmountSensitiveRead = 'commission:amount:sensitive:read',
    LaborCostRateSensitiveRead = 'labor-cost-rate:sensitive:read',
    ExceptionApprovalOpinionSensitiveRead = 'exception-approval-opinion:sensitive:read',
    LeadRead = 'lead:read',
    LeadWrite = 'lead:write',
    LeadAssign = 'lead:assign',
    LeadScoreOverride = 'lead:score:override',
    LeadSourceManage = 'lead:source:manage',
    ProjectRead = 'project:read',
    ProjectWrite = 'project:write',
    ProjectDelete = 'project:delete',
    NavDashboardView = 'nav:dashboard:view',
    NavCustomersView = 'nav:customers:view',
    NavPlatformView = 'nav:platform:view',
    NavLeadsView = 'nav:leads:view',
    NavAttachmentsView = 'nav:attachments:view',
    NavProjectsView = 'nav:projects:view',
    NavContractsView = 'nav:contracts:view',
    NavProfileView = 'nav:profile:view'
};
