/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerAliasType } from './customer-alias-type';


export interface CustomerAliasSummary {
    id: string;
    customerId: string;
    aliasName: string;
    aliasType: CustomerAliasType;
    normalizedName: string;
    isPrimary: boolean;
    createdAt: string;
    createdBy: string | null;
}
