/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum CustomerWorkspaceTimelineEventType {

    LeadUpdated = 'lead-updated',

    ProjectUpdated = 'project-updated',

    ContractUpdated = 'contract-updated',

    FollowUpRecorded = 'follow-up-recorded',

    DiscussionAdded = 'discussion-added'
}
