/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStatus } from './project-status';
import { ProjectStage } from './project-stage';


export interface CustomerWorkspaceProjectItem {
    id: string;
    projectNo: string;
    projectName: string;
    status: ProjectStatus;
    currentStage: ProjectStage;
    ownerName: string | null;
    plannedSignAt: string | null;
    updatedAt: string;
}
