/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityProvider } from './identity-provider';


export interface EnabledLoginProviderSummary {
    id: string;
    provider: IdentityProvider;
    tenantId: string | null;
    displayName: string;
    loginScopes: Array<string>;
}
