/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalDepartmentMappingStatus } from './external-department-mapping-status';


export interface ExternalDepartmentMappingSummary {
    id: string;
    sourceId: string;
    externalDepartmentId: string;
    externalParentDepartmentId: string | null;
    externalDepartmentName: string;
    orgUnitId: string | null;
    status: ExternalDepartmentMappingStatus;
    externalSnapshot: { [key: string]: any; };
    lastSeenAt: string | null;
    rowVersion: number;
    createdAt: string;
    createdBy: string | null;
    updatedAt: string;
    updatedBy: string | null;
}
