/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FreezeCommissionRoleAssignmentRequest { 
    comment?: string;
    sourceHandoverId: string;
    handoverSummarySnapshotId: string;
    expectedVersion?: number;
}

