/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HealthDependencyCheckDto {
    status: HealthDependencyCheckDtoStatusEnum;
    message: string;
    durationMs: number;
}
export enum HealthDependencyCheckDtoStatusEnum {
    Pass = 'pass',
    Fail = 'fail'
};
