/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityProviderConfigStatus } from './identity-provider-config-status';
import { IdentityProviderSearchGrantMode } from './identity-provider-search-grant-mode';
import { IdentityProvider } from './identity-provider';


export interface IdentityProviderConfigSummary {
    id: string;
    provider: IdentityProvider;
    tenantId: string | null;
    displayName: string;
    status: IdentityProviderConfigStatus;
    enabled: boolean;
    loginEnabled: boolean;
    bindingEnabled: boolean;
    searchEnabled: boolean;
    clientId: string;
    secretConfigured: boolean;
    redirectUri: string | null;
    loginScopes: Array<string>;
    searchScopes: Array<string>;
    tenantAllowlist: Array<string>;
    searchGrantMode: IdentityProviderSearchGrantMode;
    rowVersion: number;
    createdAt: string;
    createdBy: string | null;
    updatedAt: string;
    updatedBy: string | null;
}
