/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LeadOwnerAssignmentType {

    Claimed = 'claimed',

    Assigned = 'assigned',

    Reassigned = 'reassigned'
}
