/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeadConvertedProjectSummary } from './lead-converted-project-summary';
import { LeadAllowedAction } from './lead-allowed-action';
import { LeadUrgency } from './lead-urgency';
import { LeadBudgetStatus } from './lead-budget-status';
import { LeadStatus } from './lead-status';


export interface LeadDetailView {
    id: string;
    leadNo: string;
    leadName: string;
    customerId: string;
    customerName: string;
    sourceId: string;
    sourceName: string | null;
    sourceChannel: string | null;
    demandDescription: string | null;
    budgetStatus: LeadBudgetStatus;
    estimatedAmount: string | null;
    urgency: LeadUrgency;
    expectedDecisionDate: string | null;
    status: LeadStatus;
    ownerOrgId: string | null;
    ownerUserId: string | null;
    qualificationSummary: string | null;
    qualifiedAt: string | null;
    qualifiedBy: string | null;
    closedReason: string | null;
    closedAt: string | null;
    closedBy: string | null;
    convertedProjectId: string | null;
    convertedAt: string | null;
    convertedBy: string | null;
    rowVersion: number;
    createdAt: string;
    createdBy: string | null;
    updatedAt: string;
    updatedBy: string | null;
    ownerName: string | null;
    ownerOrgName: string | null;
    sourceSummary: string | null;
    convertedProjectSummary: LeadConvertedProjectSummary | null;
    allowedActions: Array<LeadAllowedAction>;
}
