/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LeadBudgetStatus {

    Unknown = 'unknown',

    NoBudget = 'no-budget',

    RoughBudget = 'rough-budget',

    BudgetConfirmed = 'budget-confirmed',

    BudgetApproved = 'budget-approved'
}
