/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeadWorkbenchFacet } from './lead-workbench-facet';
import { LeadListView } from './lead-list-view';
import { LeadWorkbenchScope } from './lead-workbench-scope';
import { LeadWorkbenchSummary } from './lead-workbench-summary';


export interface LeadListResponse {
    scope: LeadWorkbenchScope;
    items: Array<LeadListView>;
    summary: LeadWorkbenchSummary;
    facets: Array<LeadWorkbenchFacet>;
    totalItems: number;
    page: number;
    pageSize: number;
}
