/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeadRating } from './lead-rating';
import { LeadScoreHistoryItem } from './lead-score-history-item';
import { LeadEffectiveScoreSource } from './lead-effective-score-source';
import { LeadScoreOverrideSummary } from './lead-score-override-summary';


export interface LeadScoreHistoryView {
    leadId: string;
    systemScore: number;
    systemRating: LeadRating;
    scoreReason: string;
    scoreUpdatedAt: string;
    effectiveScore: number;
    effectiveRating: LeadRating;
    effectiveScoreReason: string;
    effectiveScoreSource: LeadEffectiveScoreSource;
    activeScoreOverrideId: string | null;
    activeOverride: LeadScoreOverrideSummary | null;
    pendingOverride: LeadScoreOverrideSummary | null;
    snapshots: Array<LeadScoreHistoryItem>;
    overrides: Array<LeadScoreOverrideSummary>;
}
