/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LeadScoreOverrideStatus {

    Pending = 'pending',

    Approved = 'approved',

    Rejected = 'rejected',

    Revoked = 'revoked',

    Superseded = 'superseded'
}
