/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LeadAllowedAction {

    ClaimLeadOwner = 'claim-lead-owner',

    AssignLeadOwner = 'assign-lead-owner'
}
