/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum NavigationItemType {

    Basic = 'basic',

    Group = 'group',

    Collapsable = 'collapsable',

    Divider = 'divider'
}
