/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NavigationSyncSummary { 
    targetId: NavigationSyncSummaryTargetIdEnum;
    nodeCount: number;
    routeCount: number;
    hiddenCount: number;
    disabledCount: number;
    treeChecksum: string;
    navigationKeys: Array<string>;
    routeLinks: Array<string>;
}
export enum NavigationSyncSummaryTargetIdEnum {
    PlatformNavigation = 'platform-navigation'
};



