/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OperatingRestatementSummary {
    id: string;
    projectId: string;
    periodEndSnapshotId: string;
    restatesSnapshotId: string;
    restatedSnapshotId: string;
    restatementReason: string;
    restatementSummary: string;
    status: OperatingRestatementSummaryStatusEnum;
    handledAt: string;
    handledBy: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
}
export enum OperatingRestatementSummaryStatusEnum {
    Active = 'active',
    Superseded = 'superseded',
    Voided = 'voided'
};
