/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSyncRunStatus } from './org-sync-run-status';


export interface OrgSyncRunSummary {
    id: string;
    sourceId: string;
    status: OrgSyncRunStatus;
    requestedBy: string | null;
    startedAt: string;
    finishedAt: string | null;
    totalItemCount: number;
    approvedItemCount: number;
    skippedItemCount: number;
    failedItemCount: number;
    errorSummary: string | null;
    requestSnapshot: { [key: string]: any; };
    resultSummary: { [key: string]: any; };
    rowVersion: number;
    createdAt: string;
    createdBy: string | null;
    updatedAt: string;
    updatedBy: string | null;
}
