/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OwnerReferenceUser {
    id: string;
    displayName: string;
    isActive: boolean;
    primaryOrgUnitId: string | null;
    primaryOrgUnitName: string | null;
}
