/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentRecordStatus } from './payment-record-status';


export interface PaymentRecordSummary { 
    id: string;
    projectId: string;
    contractId: string | null;
    paymentAmount: string;
    paymentDate: string;
    costCategory: string;
    sourceType: string;
    status: PaymentRecordStatus;
    confirmedAt: string | null;
    confirmedBy: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
}



