/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlatformUserSummary { 
    id: string;
    username: string;
    displayName: string;
    email: string | null;
    phone: string | null;
    isActive: boolean;
    primaryOrgUnitId: string | null;
    primaryOrgUnitName: string | null;
    roleNames: Array<string>;
    createdAt: string;
    updatedAt: string;
}

