/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlatformPermissionSummary { 
    key: PlatformPermissionSummaryKeyEnum;
    name: string;
    description: string;
    group: string;
    status: PlatformPermissionSummaryStatusEnum;
    isSystemPermission: boolean;
    sourceType: PlatformPermissionSummarySourceTypeEnum;
    deprecatedBy: PlatformPermissionSummaryDeprecatedByEnum | null;
}
export enum PlatformPermissionSummaryKeyEnum {
    PlatformUsersManage = 'platform:users:manage',
    PlatformRolesManage = 'platform:roles:manage',
    PlatformNavigationManage = 'platform:navigation:manage',
    PlatformOrgUnitsManage = 'platform:org-units:manage',
    CommissionRuleVersionsManage = 'commission:rule-versions:manage',
    CommissionAssignmentsManage = 'commission:assignments:manage',
    CommissionCalculationsManage = 'commission:calculations:manage',
    CommissionPayoutsManage = 'commission:payouts:manage',
    CommissionAdjustmentsManage = 'commission:adjustments:manage',
    ContractFinanceManage = 'contract:finance:manage',
    ProjectRead = 'project:read',
    ProjectWrite = 'project:write',
    ProjectDelete = 'project:delete',
    NavDashboardView = 'nav:dashboard:view',
    NavPlatformView = 'nav:platform:view',
    NavProjectsView = 'nav:projects:view',
    NavContractsView = 'nav:contracts:view',
    NavProfileView = 'nav:profile:view'
};
export enum PlatformPermissionSummaryStatusEnum {
    Active = 'active',
    Inactive = 'inactive',
    Deprecated = 'deprecated'
};
export enum PlatformPermissionSummarySourceTypeEnum {
    SystemSeeded = 'system-seeded'
};
export enum PlatformPermissionSummaryDeprecatedByEnum {
    PlatformUsersManage = 'platform:users:manage',
    PlatformRolesManage = 'platform:roles:manage',
    PlatformNavigationManage = 'platform:navigation:manage',
    PlatformOrgUnitsManage = 'platform:org-units:manage',
    CommissionRuleVersionsManage = 'commission:rule-versions:manage',
    CommissionAssignmentsManage = 'commission:assignments:manage',
    CommissionCalculationsManage = 'commission:calculations:manage',
    CommissionPayoutsManage = 'commission:payouts:manage',
    CommissionAdjustmentsManage = 'commission:adjustments:manage',
    ContractFinanceManage = 'contract:finance:manage',
    ProjectRead = 'project:read',
    ProjectWrite = 'project:write',
    ProjectDelete = 'project:delete',
    NavDashboardView = 'nav:dashboard:view',
    NavPlatformView = 'nav:platform:view',
    NavProjectsView = 'nav:projects:view',
    NavContractsView = 'nav:contracts:view',
    NavProfileView = 'nav:profile:view'
};



