/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectBidCommercialMaterialItemView {
    materialKey: string;
    label: string;
    materialStatus: ProjectBidCommercialMaterialItemViewMaterialStatusEnum;
    responsibleRole: string | null;
    dueAt: string | null;
    blocksNextStep: boolean;
    navigationHint: string | null;
    sortOrder: number;
    id: string;
    processId: string;
}
export enum ProjectBidCommercialMaterialItemViewMaterialStatusEnum {
    Missing = 'missing',
    InProgress = 'in-progress',
    Ready = 'ready',
    NotRequired = 'not-required'
};
