/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';
import { OperatingRiskLevel } from './operating-risk-level';
import { OperatingDataMaturityLevel } from './operating-data-maturity-level';
import { SensitiveStringFieldProjection } from './sensitive-string-field-projection';


export interface ProjectVarianceRiskExplanationView {
    projectId: string;
    signalEvaluationId: string;
    varianceSourceSummaryProjection: SensitiveStringFieldProjection;
    riskLevel: OperatingRiskLevel;
    taxImpactSummaryProjection: SensitiveStringFieldProjection;
    allocationStabilitySummary: string | null;
    unmappedCostSummary: string | null;
    dataMaturityLevel: OperatingDataMaturityLevel;
    costActionRecommendation: OperatingSnapshotActionLevel;
    currentActionLevel: OperatingSnapshotActionLevel;
    referencedBaselineVersion: string;
    referencedSnapshotVersion: string;
    recommendedActionSummary: string | null;
    allowedActions: Array<string>;
}
