/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractHandoverEffectiveContractSetSummary } from './contract-handover-effective-contract-set-summary';
import { ProjectHandoverParticipantConfirmationSummary } from './project-handover-participant-confirmation-summary';
import { ProjectHandoverReceiptJudgmentModeSummary } from './project-handover-receipt-judgment-mode-summary';
import { ContractHandoverCurrentBaselineSummary } from './contract-handover-current-baseline-summary';


export interface ProjectHandoverDetailView {
    handoverId: string | null;
    projectId: string;
    projectCode: string;
    projectName: string;
    handoverStatus: ProjectHandoverDetailViewHandoverStatusEnum;
    confirmedAt: string | null;
    confirmedBy: string | null;
    comment: string | null;
    rowVersion: number | null;
    effectiveContractSetSummary: ContractHandoverEffectiveContractSetSummary;
    contractSummarySnapshotId: string | null;
    currentHandoverBaselineSummary: ContractHandoverCurrentBaselineSummary;
    participantConfirmationSummary: ProjectHandoverParticipantConfirmationSummary;
    receiptJudgmentModeSummary: ProjectHandoverReceiptJudgmentModeSummary;
    summaryPackageKey: string | null;
    summarySnapshotId: string | null;
    projectionLevel: string | null;
    exportPolicy: string | null;
    allowedActions: Array<string>;
    blockingReasons: Array<string>;
    generatedAt: string;
}
export enum ProjectHandoverDetailViewHandoverStatusEnum {
    NotStarted = 'not_started',
    Draft = 'draft',
    Confirmed = 'confirmed',
    Superseded = 'superseded',
    Voided = 'voided'
};
