/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeadStatus } from './lead-status';


export interface ProjectSourceLeadSummary {
    id: string;
    leadNo: string;
    leadName: string;
    customerName: string;
    status: LeadStatus;
}
