/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStatus } from './project-status';
import { ProjectTechnicalCostItemView } from './project-technical-cost-item-view';
import { ProjectTechnicalRiskItemView } from './project-technical-risk-item-view';
import { ProjectStage } from './project-stage';
import { ProjectTechnicalCostPackageSummary } from './project-technical-cost-package-summary';
import { ProjectTechnicalScopeItemView } from './project-technical-scope-item-view';


export interface ProjectTechnicalCostWorkspaceView {
    projectId: string;
    currentStage: ProjectStage;
    status: ProjectStatus;
    currentPackage: ProjectTechnicalCostPackageSummary | null;
    scopeItems: Array<ProjectTechnicalScopeItemView>;
    riskItems: Array<ProjectTechnicalRiskItemView>;
    costItems: Array<ProjectTechnicalCostItemView>;
    blockingReasons: Array<string>;
    nextStep: string;
    ownerLabel: string;
    allowedActions: Array<string>;
    generatedAt: string;
}
