/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ProjectStage {

    Assessment = 'assessment',

    ScopeConfirmation = 'scope-confirmation',

    CommercialClosure = 'commercial-closure',

    Contracting = 'contracting',

    Handover = 'handover',

    Execution = 'execution',

    Acceptance = 'acceptance',

    Completed = 'completed',

    ClosedLost = 'closed-lost',

    ClosedTerminated = 'closed-terminated'
}
