/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ProjectActualCostSourceType {

    PaymentRecord = 'PAYMENT_RECORD',

    InvoiceRecord = 'INVOICE_RECORD',

    ExpenseRecord = 'EXPENSE_RECORD',

    PayableRecord = 'PAYABLE_RECORD',

    Labor = 'LABOR'
}
