/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectTimelineEvent } from './project-timeline-event';


export interface ProjectTimelineView {
    projectId: string;
    events: Array<ProjectTimelineEvent>;
    generatedAt: string;
}
