/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectPricingMarginConditionItemInput {
    conditionKey: string;
    conditionType: ProjectPricingMarginConditionItemInputConditionTypeEnum;
    label: string;
    conditionSummary: string;
    conditionStatus: ProjectPricingMarginConditionItemInputConditionStatusEnum;
    requiredForContracting?: boolean;
    responsibleRole?: string | null;
    dueAt?: string | null;
    resolutionSummary?: string | null;
    sortOrder?: number;
}
export enum ProjectPricingMarginConditionItemInputConditionTypeEnum {
    Financial = 'financial',
    Tax = 'tax',
    Payment = 'payment',
    Scope = 'scope',
    Risk = 'risk',
    Approval = 'approval'
};
export enum ProjectPricingMarginConditionItemInputConditionStatusEnum {
    Open = 'open',
    Closed = 'closed',
    Waived = 'waived'
};
