/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';
import { BaselineSelectionSource } from './baseline-selection-source';


export interface ProjectOperatingSnapshotSummary { 
    id: string;
    projectId: string;
    snapshotMode: ProjectOperatingSnapshotSummarySnapshotModeEnum;
    snapshotAt: string;
    sourceWindowStart: string | null;
    sourceWindowEnd: string | null;
    effectiveContractTotal: string;
    receivableConfirmedTotal: string;
    includedCostTotal: string;
    originalBaselineCost: string;
    currentEffectiveBaselineCost: string;
    grossMarginAmount: string;
    grossMarginRate: string | null;
    taxImpactSummary: string;
    taxImpactPendingAmount: string;
    allocationStabilitySummary: string | null;
    unmappedCostSummary: string | null;
    currentActionLevel: OperatingSnapshotActionLevel;
    referencedBaselineVersion: string;
    baselineSelectionSource: BaselineSelectionSource;
    handoverRebaselineRecordId: string | null;
    status: ProjectOperatingSnapshotSummaryStatusEnum;
    supersedesId: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
}
export enum ProjectOperatingSnapshotSummarySnapshotModeEnum {
    Realtime = 'realtime',
    PeriodEnd = 'period-end',
    Restated = 'restated'
};
export enum ProjectOperatingSnapshotSummaryStatusEnum {
    Active = 'active',
    Superseded = 'superseded',
    Voided = 'voided'
};



