/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectHandoverReceiptJudgmentModeSummary {
    status: ProjectHandoverReceiptJudgmentModeSummaryStatusEnum;
    receiptJudgmentMode: string | null;
    sourceType: ProjectHandoverReceiptJudgmentModeSummarySourceTypeEnum;
    sourceId: string | null;
    summary: string;
}
export enum ProjectHandoverReceiptJudgmentModeSummaryStatusEnum {
    NotFrozen = 'not_frozen',
    Frozen = 'frozen'
};
export enum ProjectHandoverReceiptJudgmentModeSummarySourceTypeEnum {
    ProjectHandover = 'project-handover',
    ProjectReceiptJudgmentFreeze = 'project-receipt-judgment-freeze',
    None = 'none'
};
