/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectActualCostRecordDetailView {
    id: string;
    projectId: string;
    recordNo: string | null;
    costType: ProjectActualCostRecordDetailViewCostTypeEnum;
    costSubtype: string | null;
    occurredOn: string | null;
    accountingPeriod: string | null;
    registeredAt: string | null;
    confirmedAt: string | null;
    includedAt: string | null;
    executionStageCode: string | null;
    stageDerivedFromType: string | null;
    stageDerivedFromId: string | null;
    stageDerivedAt: string | null;
    stageLockedAt: string | null;
    currency: string;
    amountExcludingTax: string | null;
    taxCostAmount: string | null;
    amountIncludingTax: string | null;
    recordStatus: ProjectActualCostRecordDetailViewRecordStatusEnum;
    isIncludedInProjectCost: boolean;
    isHighRisk: boolean;
    sourceType: string | null;
    sourceId: string | null;
    sourceRefNo: string | null;
    evidenceSummary: string | null;
    attachmentCount: number;
    registeredBy: string | null;
    confirmedBy: string | null;
    includedBy: string | null;
    ownerRole: string | null;
    costDescription: string | null;
    taxImpactSummary: string | null;
    riskNote: string | null;
    supersedesRecordId: string | null;
    voidReason: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
    sourceStatusSummary: string | null;
    effectivePeriodSummary: string | null;
    measurementBasisSummary: string | null;
    supersedesSummary: string | null;
    allowedActions: Array<string>;
    laborPersonId: string | null;
    laborRole: string | null;
    laborPeriodType: ProjectActualCostRecordDetailViewLaborPeriodTypeEnum | null;
    laborPeriodStart: string | null;
    laborPeriodEnd: string | null;
    actualHours: string | null;
    actualPersonDays: string | null;
    internalCostRate: string | null;
    rateVersionId: string | null;
    laborAmount: string | null;
    workSummary: string | null;
    deliveryStage: string | null;
}
export enum ProjectActualCostRecordDetailViewCostTypeEnum {
    Procurement = 'PROCUREMENT',
    Invoice = 'INVOICE',
    Expense = 'EXPENSE',
    PaymentFact = 'PAYMENT_FACT',
    Labor = 'LABOR'
};
export enum ProjectActualCostRecordDetailViewRecordStatusEnum {
    Draft = 'DRAFT',
    Registered = 'REGISTERED',
    Confirmed = 'CONFIRMED',
    Included = 'INCLUDED',
    Voided = 'VOIDED',
    Replaced = 'REPLACED'
};
export enum ProjectActualCostRecordDetailViewLaborPeriodTypeEnum {
    Week = 'WEEK',
    Month = 'MONTH'
};
