/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStatus } from './project-status';
import { ProjectStage } from './project-stage';


export interface ProjectListView {
    id: string;
    projectNo: string;
    projectName: string;
    customerId: string | null;
    customerName: string | null;
    customerProjectNo: string | null;
    currentStage: ProjectStage;
    status: ProjectStatus;
    ownerOrgName: string | null;
    ownerName: string | null;
    latestMilestoneAt: string | null;
    createdAt: string;
}
