/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';


export interface ProjectBusinessOutcomeOverviewView { 
    projectId: string;
    effectiveContractSetSummary: string;
    receivableConfirmedAmountSummary: string;
    includedCostTotalSummary: string;
    currentEffectiveBaselineCostSummary: string;
    grossMarginSummary: string;
    taxImpactSummary: string;
    allocationStabilitySummary: string | null;
    unmappedCostSummary: string | null;
    dataMaturityLevel: string;
    currentActionLevel: OperatingSnapshotActionLevel;
    referencedBaselineVersion: string;
    referencedSnapshotVersion: string;
    allowedActions: Array<string>;
}



