/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStatus } from './project-status';
import { ProjectStage } from './project-stage';


export interface ProjectDetailStageSummary {
    currentStage: ProjectStage;
    status: ProjectStatus;
    plannedSignAt: string | null;
    closedAt: string | null;
    closedReason: string | null;
    blockingReasons: Array<string>;
}
