/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectHandoverReceiptJudgmentSourceType } from './project-handover-receipt-judgment-source-type';
import { ProjectHandoverReceiptJudgmentFreezeStatus } from './project-handover-receipt-judgment-freeze-status';


export interface ProjectHandoverReceiptJudgmentModeSummary {
    status: ProjectHandoverReceiptJudgmentFreezeStatus;
    receiptJudgmentMode: string | null;
    sourceType: ProjectHandoverReceiptJudgmentSourceType;
    sourceId: string | null;
    summary: string;
}
