/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectBidCommercialProcessSummary {
    id: string;
    projectId: string;
    version: number;
    isCurrent: boolean;
    supersedesId: string | null;
    status: ProjectBidCommercialProcessSummaryStatusEnum;
    bidMode: ProjectBidCommercialProcessSummaryBidModeEnum;
    currentStage: ProjectBidCommercialProcessSummaryCurrentStageEnum;
    decision: ProjectBidCommercialProcessSummaryDecisionEnum;
    resultStatus: ProjectBidCommercialProcessSummaryResultStatusEnum;
    processSummary: string;
    decisionSummary: string | null;
    resultSummary: string | null;
    tenderNo: string | null;
    bidPackageNo: string | null;
    ownerRole: string | null;
    blockerCount: number;
    effectiveAt: string;
    createdAt: string;
    createdBy: string | null;
    updatedAt: string;
    updatedBy: string | null;
    rowVersion: number;
}
export enum ProjectBidCommercialProcessSummaryStatusEnum {
    Effective = 'effective',
    Superseded = 'superseded'
};
export enum ProjectBidCommercialProcessSummaryBidModeEnum {
    PublicTender = 'public-tender',
    Invitation = 'invitation',
    Comparison = 'comparison',
    CommercialNegotiation = 'commercial-negotiation',
    CompetitiveNegotiation = 'competitive-negotiation',
    DirectCommercial = 'direct-commercial',
    NotRequired = 'not-required'
};
export enum ProjectBidCommercialProcessSummaryCurrentStageEnum {
    NotStarted = 'not-started',
    Preparation = 'preparation',
    Submitted = 'submitted',
    Negotiating = 'negotiating',
    ResultConfirmed = 'result-confirmed',
    Closed = 'closed'
};
export enum ProjectBidCommercialProcessSummaryDecisionEnum {
    Pending = 'pending',
    Participate = 'participate',
    NoBid = 'no-bid',
    NotRequired = 'not-required'
};
export enum ProjectBidCommercialProcessSummaryResultStatusEnum {
    Pending = 'pending',
    Won = 'won',
    Lost = 'lost',
    Cancelled = 'cancelled',
    NotApplicable = 'not-applicable'
};
