/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';
import { OperatingDataMaturityLevel } from './operating-data-maturity-level';
import { SensitiveStringFieldProjection } from './sensitive-string-field-projection';


export interface ProjectBusinessOutcomeOverviewView {
    projectId: string;
    effectiveContractSetSummaryProjection: SensitiveStringFieldProjection;
    receivableConfirmedAmountSummaryProjection: SensitiveStringFieldProjection;
    includedCostTotalSummaryProjection: SensitiveStringFieldProjection;
    currentEffectiveBaselineCostSummaryProjection: SensitiveStringFieldProjection;
    grossMarginAmountProjection: SensitiveStringFieldProjection;
    grossMarginRateProjection: SensitiveStringFieldProjection;
    taxImpactSummaryProjection: SensitiveStringFieldProjection;
    allocationStabilitySummary: string | null;
    unmappedCostSummary: string | null;
    dataMaturityLevel: OperatingDataMaturityLevel;
    currentActionLevel: OperatingSnapshotActionLevel;
    referencedBaselineVersion: string;
    referencedSnapshotVersion: string;
    allowedActions: Array<string>;
}
