/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensitiveStringFieldProjection } from './sensitive-string-field-projection';


export interface ProjectDetailContractSummary {
    activeContractCount: number;
    latestContractId: string | null;
    latestContractNo: string | null;
    latestContractStatus: string | null;
    signedAmount: string | null;
    signedAmountProjection: SensitiveStringFieldProjection;
    currencyCode: string | null;
    signedAt: string | null;
    currentSnapshotId: string | null;
}
