/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';
import { OperatingSnapshotMode } from './operating-snapshot-mode';
import { BaselineSelectionSource } from './baseline-selection-source';
import { OperatingLifecycleStatus } from './operating-lifecycle-status';


export interface ProjectOperatingSnapshotSummary {
    id: string;
    projectId: string;
    snapshotMode: OperatingSnapshotMode;
    snapshotAt: string;
    sourceWindowStart: string | null;
    sourceWindowEnd: string | null;
    effectiveContractTotal: string;
    receivableConfirmedTotal: string;
    includedCostTotal: string;
    originalBaselineCost: string;
    currentEffectiveBaselineCost: string;
    grossMarginAmount: string;
    grossMarginRate: string | null;
    taxImpactSummary: string;
    taxImpactPendingAmount: string;
    allocationStabilitySummary: string | null;
    unmappedCostSummary: string | null;
    currentActionLevel: OperatingSnapshotActionLevel;
    referencedBaselineVersion: string;
    baselineSelectionSource: BaselineSelectionSource;
    handoverRebaselineRecordId: string | null;
    status: OperatingLifecycleStatus;
    supersedesId: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
}
