/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReclassifyCostStageAttributionRequest { 
    newAttributedStage: string;
    lockedBySnapshotId?: string | null;
    reclassifyReason: string;
    comment?: string | null;
    expectedVersion?: number;
}

