/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterRetentionCommissionPayoutRequest } from './register-retention-commission-payout-request';
import { NonRetentionCommissionPayoutStage } from './non-retention-commission-payout-stage';
import { RegisterNonRetentionCommissionPayoutRequest } from './register-non-retention-commission-payout-request';


/**
 * @type RegisterCommissionPayoutRequest
 * @export
 */
export type RegisterCommissionPayoutRequest = RegisterNonRetentionCommissionPayoutRequest | RegisterRetentionCommissionPayoutRequest;
