/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterNonRetentionCommissionPayoutRequest { 
    approvalRecordId?: string;
    paidRecordAmount: string;
    paidAt?: string;
    comment?: string;
    expectedVersion?: number;
    payoutStage: RegisterNonRetentionCommissionPayoutRequestPayoutStageEnum;
    summarySnapshotId?: string;
}
export enum RegisterNonRetentionCommissionPayoutRequestPayoutStageEnum {
    First = 'first',
    Second = 'second',
    Final = 'final'
};
