/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalesFollowUpOutcome } from './sales-follow-up-outcome';


export interface ReplaceSalesFollowUpRecordRequest {
    followUpType: string;
    occurredAt: string;
    summary: string;
    detail?: string | null;
    outcome: SalesFollowUpOutcome;
    nextFollowUpAt?: string | null;
    ownerOrgId?: string | null;
    ownerUserId?: string | null;
    replacementReason: string;
    expectedVersion: number;
}
