/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatingSnapshotActionLevel } from './operating-snapshot-action-level';
import { BaselineSelectionSource } from './baseline-selection-source';


export interface ReviewCommissionGateBindingRequest { 
    bindingAction: OperatingSnapshotActionLevel;
    gateReviewDecision: string;
    blockingReasonCode?: string | null;
    baselineSelectionSource: BaselineSelectionSource;
    summaryPackageKey: string;
    summarySnapshotId: string;
    referencedBaselineVersion: string;
    referencedSnapshotVersion: string;
    comment?: string | null;
    expectedVersion?: number;
}
