/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalesIntelligenceGapItem } from './sales-intelligence-gap-item';
import { SalesIntelligenceGapSeverity } from './sales-intelligence-gap-severity';


export interface SalesIntelligenceGapSummary {
    item: SalesIntelligenceGapItem;
    label: string;
    isMissing: boolean;
    explanation: string;
    severity: SalesIntelligenceGapSeverity;
}
