/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnitOrg } from './unit-org';


export interface SanitizedUserWithOrgUnits { 
    id: string;
    displayName: string;
    username: string;
    roles: Array<string>;
    permissions: Array<SanitizedUserWithOrgUnitsPermissionsEnum>;
    email: string | null;
    avatarUrl: string | null;
    isActive: boolean;
    lastLoginAt: string | null;
    emailVerified: boolean;
    phoneVerified: boolean;
    phone: string | null;
    orgUnits: Array<UnitOrg>;
}
export enum SanitizedUserWithOrgUnitsPermissionsEnum {
    PlatformUsersManage = 'platform:users:manage',
    PlatformRolesManage = 'platform:roles:manage',
    PlatformNavigationManage = 'platform:navigation:manage',
    PlatformOrgUnitsManage = 'platform:org-units:manage',
    ProjectRead = 'project:read',
    ProjectWrite = 'project:write',
    ProjectDelete = 'project:delete',
    NavDashboardView = 'nav:dashboard:view',
    NavPlatformView = 'nav:platform:view',
    NavProjectsView = 'nav:projects:view',
    NavContractsView = 'nav:contracts:view',
    NavProfileView = 'nav:profile:view'
};



