/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum SensitiveFieldPackageKey {

    ContractFinance = 'contract-finance',

    OperatingFinance = 'operating-finance',

    CommissionCompensation = 'commission-compensation',

    LaborCostRate = 'labor-cost-rate',

    ExceptionApprovalOpinion = 'exception-approval-opinion'
}
