/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SharedCostAllocationResultSummary } from './shared-cost-allocation-result-summary';


export interface SharedCostAllocationBasisSummary { 
    id: string;
    sourceCostScopeKey: string;
    basisType: string;
    allocationMethod: string;
    basisSummary: string | null;
    status: SharedCostAllocationBasisSummaryStatusEnum;
    effectiveAt: string | null;
    effectiveBy: string | null;
    supersedesId: string | null;
    rowVersion: number;
    createdAt: string;
    updatedAt: string;
    results: Array<SharedCostAllocationResultSummary>;
}
export enum SharedCostAllocationBasisSummaryStatusEnum {
    Pending = 'pending',
    Active = 'active',
    Superseded = 'superseded',
    Voided = 'voided'
};



