/**
 * POMS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommissionPayoutStage } from './commission-payout-stage';


export interface SubmitCommissionPayoutApprovalRequest { 
    payoutStage?: CommissionPayoutStage;
    gateReviewRecordId?: string;
    freezeVersionId?: string;
    baselineSelectionSource?: string;
    summarySnapshotId?: string;
    retentionReceiptRecordId?: string;
    departureExceptionDecisionId?: string;
    comment?: string;
    expectedVersion?: number;
}
