/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemSettingKey } from './system-setting-key';
import { SystemSettingValueType } from './system-setting-value-type';


export interface SystemSettingSummary {
    key: SystemSettingKey;
    displayName: string;
    description: string;
    group: string;
    valueType: SystemSettingValueType;
    value: number;
    defaultValue: number;
    minValue: number | null;
    maxValue: number | null;
    unit: string | null;
    rowVersion: number;
    updatedAt: string | null;
    updatedBy: string | null;
}
