/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum TodoSourceType {

    ApprovalRecord = 'approval-record',

    ConfirmationRecord = 'confirmation-record',

    SalesFollowUpRecord = 'sales-follow-up-record'
}
