/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentStorageProviderConfigStatus } from './attachment-storage-provider-config-status';


export interface UpdateAttachmentStorageProviderConfigRequest {
    displayName?: string;
    enabled?: boolean;
    status?: AttachmentStorageProviderConfigStatus;
    endpoint?: string | null;
    region?: string | null;
    bucket?: string | null;
    keyPrefix?: string | null;
    forcePathStyle?: boolean;
    accessKeyId?: string | null;
    secretAccessKey?: string | null;
    expectedVersion?: number;
}
