/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalOrgSourceStatus } from './external-org-source-status';


export interface UpdateExternalOrgSourceRequest {
    displayName?: string;
    status?: ExternalOrgSourceStatus;
    providerConfigId?: string | null;
    authoritativeOrgUnitId?: string | null;
    externalRootDepartmentId?: string | null;
    syncScopes?: Array<string>;
    expectedVersion?: number;
}
