/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSalesDiscoveryRecordRequest {
    procurementProcess?: string | null;
    budgetSource?: string | null;
    customerPainPoints?: string | null;
    decisionCycle?: string | null;
    nextContactPlan?: string | null;
    remark?: string | null;
}
