/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateContractBasicInfoRequest {
    signedAmount?: string;
    currencyCode?: string;
    signedAt?: string | null;
    retentionDueDate?: string | null;
    updatedBy?: string | null;
}
