/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseSourceType } from './expense-source-type';
import { ExpenseCategory } from './expense-category';


export interface UpdateExpenseRecordRequest {
    contractId?: string | null;
    expenseCategory?: ExpenseCategory;
    expenseDescription?: string;
    expenseDate?: string;
    currency?: string;
    amountIncludingTax?: string;
    taxAmount?: string | null;
    amountExcludingTax?: string | null;
    sourceType?: ExpenseSourceType;
    evidenceSummary?: string | null;
    attachmentCount?: number;
    expectedVersion?: number;
}
