/**
 * POMS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserOrgUnitMembershipType } from './user-org-unit-membership-type';


export interface UserOrgUnitSummary {
    id: string;
    name: string;
    code: string | null;
    description: string | null;
    membershipType: UserOrgUnitMembershipType;
}
